### ISSUE TITLE
Provider Event Listeners not working

### ISSUE THREAD

**Issue by Omar-Aziz** [tmm/wagmi#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.1

### Current Behavior

The following should detect account change:

```JavaScript
provider.on("accountsChanged", (accounts) => {
    console.log("accountsChanged", accounts);
})
// This also should work
provider.once("accountsChanged", (accounts) => {
    console.log("accountsChanged", accounts);
})
```
However neither works. When using `window.ethereum` instead of the wagmi provider, it works.
I'm using the official example provided in the package.

### Expected Behavior

Should emit account change activity.

### Steps To Reproduce

```JavaScript
provider.on("accountsChanged", (accounts) => {
    console.log("accountsChanged", accounts);
})
```

**Comment by tmm** [comment]
Where does `provider` in your example come from?

You probably want to use the `connector` from `useAccount` (or general `useContext`).

Here's a basic example:

```
const [{ data }] = useAccount()
const connector = data?.connector

React.useEffect(() => {
  const onChange = (data) => console.log(data)

  connector.on('change', onChange)
  return () => {
    if (!connector) return
    connector.off('change', onChange)
  }
}, [])
```

**Comment by Omar-Aziz** [comment]
Thanks! What you suggested worked.

To answer your question, provider is coming from the same package.

```js
const provider = useProvider()

React.useEffect(() => {
  provider.on("accountsChanged", (accounts) => {
    console.log("accountsChanged", accounts);
  })
}, []}
```

Is there a reason why this doesn't work? I'm trying to follow the one that matches the documentation on ethers.js. If it won't work then what is the `useProvider()` supposed to be for?

**Comment by tmm** [comment]
Provider returns an ethers.js interface for reading/writing data. [Connectors](https://wagmi-xyz.vercel.app/docs/connectors) are used for managing wallet connections, listening to account/chain changes, etc.
