### ISSUE TITLE
Duplicate Requests `Fetch finished loading: POST "https://mainnet.infura.io/v3/.

### ISSUE THREAD

**Issue by shunkakinoki** [tmm/wagmi#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.0

### Current Behavior

It shows duplicate fetch requests upon route transition in next.js
What is the `getUrl` and is there any way i can deduplicate the requests

<img width="633" alt="Screen Shot 2022-01-24 at 3 47 43 PM" src="https://user-images.githubusercontent.com/39187513/150884229-40d12242-6fe5-4494-a2a5-43a756532ae0.png">

**Comment by shunkakinoki** [comment]
The stack trace shows below

```
| eval | @ | geturl.js:35
-- | -- | -- | --
  | eval | @ | geturl.js:13
  | __awaiter | @ | geturl.js:9
  | getUrl | @ | geturl.js:18
  | eval | @ | index.js:182
  ```

**Comment by tmm** [comment]
Happy to take a look if you create a [CodeSandbox](https://codesandbox.io) with a basic example!

**Comment by shunkakinoki** [comment]
Got it! Thank you so much for your work and support!

**Comment by tmm** [comment]
@shunkakinoki any luck on a basic example?

**Comment by shunkakinoki** [comment]
@tmm thank you for the mention! 

can you wait until the week? sorry for the delay

**Comment by shunkakinoki** [comment]
Just fixed the error... 

It was on my implementation, sorry for the unncessary error.

Thank you again for your awesome work!
