### ISSUE TITLE
[bug] Component re-render infinitely when using useContractRead with "allowance" function

### ISSUE THREAD

**Issue by pyk** [tmm/wagmi#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.1

### Current Behavior

Component re-render infinitely

### Expected Behavior

Component rerender only when data is not loaded

### Steps To Reproduce

[Here is codesandbox](https://codesandbox.io/s/cold-hill-xzsu7?file=/src/App.js)

### Anything else?

Nope

**Comment by pyk** [comment]
Simple react app to reproduce the bug:

```
import "./styles.css";

import { Provider, useContractRead, erc20ABI } from "wagmi";

function Allowance() {
  // Get token allowance
  const [allowanceData] = useContractRead(
    {
      addressOrName: "0x6b175474e89094c44da98b954eedeac495271d0f",
      contractInterface: erc20ABI
    },
    "allowance",
    {
      args: [
        "0xa13c0c8eb109f5a13c6c90fc26afb23beb3fb04a",
        "0xba12222222228d8ba445958a75a0704d566bf2c8"
      ]
    }
  );
  console.debug("allowanceData", allowanceData);

  return <div>hellow</div>;
}

export default function App() {
  return (
    <Provider>
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        <Allowance />
      </div>
    </Provider>
  );
}

```

**Comment by tmm** [comment]
`useContractRead` does not deep compare `args` so if you use an array you should make sure it is stable (i.e. React.useMemo, hoist outside of render, etc.). Here's an example [CodeSandbox](https://codesandbox.io/s/gifted-sunset-d2ct0?file=/src/App.tsx).

Future optimization to wagmi will include this.

**Comment by pyk** [comment]
ty ser @tmm

**Comment by rsodre** [comment]
> useContractRead does not deep compare args so if you use an array you should make sure it is stable (i.e. React.useMemo, hoist outside of render, etc.). Here's an example [CodeSandbox](https://codesandbox.io/s/gifted-sunset-d2ct0?file=/src/App.tsx).

> Future optimization to wagmi will include this.

@tmm Has any improvement been made on this already? Or do we still need to memoize args arrays?

**Comment by tmm** [comment]
@rsodre you shouldn't need to memoize `args` anymore. try it out.
