### ISSUE TITLE
[bug] useAccount should return a checksummed address

### ISSUE THREAD

**Issue by sammdec** [tmm/wagmi#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.1

### Current Behavior

When a wallet is connected the `useAccount` hook returns an address, but this address is not checksummed.

### Expected Behavior

It would be much more canonical if the address returned was in the checksummed format.

### Steps To Reproduce

1. Connect wallet (to metamask)
2. Look at address returned

### Anything else?

Not sure if this is dependent on the connector but it would be good to normalise thise

**Comment by tmm** [comment]
Good catch! Added checksumming for `connector.connect` via `connector.getAccount` ([inject](https://github.com/tmm/wagmi/blob/main/packages/private/src/connectors/injected.ts#L74-L75), [WalletConnect](https://github.com/tmm/wagmi/blob/main/packages/private/src/connectors/walletConnect.ts#L74-L75), [WalletLink](https://github.com/tmm/wagmi/blob/main/packages/private/src/connectors/walletLink.ts#L77-L78)), but am missing in a couple other places.

**Comment by sammdec** [comment]
@tmm Got a PR up here https://github.com/tmm/wagmi/pull/120
Fixed by #120
