### ISSUE TITLE
[bug]?? API Keys exposed in Remix example

### ISSUE THREAD

**Issue by epitaphmike** [tmm/wagmi#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.9

### Current Behavior

When using the existing Remix example the `alchemy`, `etherscan`, `infuraId` API keys stored in the `.env` files are exposed to the client allowing anyone access to the keys. This seems like this shouldn't be the case given some api keys are not for free accounts. Am I missing something here?

The keys are returned from the loader function
```javascript
export function loader() {
  require('dotenv').config()
  return {
    alchemy: process.env.REMIX_ALCHEMY_ID as string,
    etherscan: process.env.REMIX_ETHERSCAN_API_KEY as string,
    infuraId: process.env.REMIX_INFURA_ID as string,
  }
}
```
and exposed via the `provider` in the `App()`

```javascript
const provider = ({ chainId }: ProviderConfig) =>
    providers.getDefaultProvider(
      isChainSupported(chainId) ? chainId : defaultChain.id,
      {
        alchemy,
        etherscan,
        infuraId,
      },
    )
```

Even in the build these keys are easily found by searching for `getDefaultProvider`.

```javascript
provider: ({chainId: x})=>Tg.providers.getDefaultProvider(s(x) ? x : i.id, {
            alchemy: t,
            etherscan: e,
            infuraId: r
        }),
```

**Comment by tmm** [comment]
Thanks for raising this! Those keys are client publishable keys and not secret keys. Most providers (i.e. Alchemy, Infura, etc.) also allow for restricting access to specific origins.

**Comment by epitaphmike** [comment]
I am trying to whitelist the domain for the alchemy key but it seems the referrer is the server not the client. I checked with alchemy support and they gave me a list of IP addresses that were of my server location. Any ideas? I have implemented the WAGMI client as per the documentation.

**Comment by bakeiro** [comment]
@epitaphmike that problems sounds like a Alchemy problem, not like a wagmi problem, since that its related with IP restrictions/alchemy features...

**Comment by bakeiro** [comment]
apart of that, I have a doubt... if the provider restrictions are not enough (in case attacker can bypass the domain restriction for example)
then I guess most safest option, would be having something like a "backend provider", a provider which consist in a backend server which receives the client request, and with the secret API key can query the blockchain, and sends back to the client the response.
that way key it's never exposed in frontend and users can interact easily from the frontend, is this something doable that makes sense??

**Comment by tmm** [comment]
You could proxy requests to Alchemy from your own RPC server and use [`jsonRpcProvider`](https://mirror-nox6386.slack.com/archives/C03E66SRAFM/p1658520217077189) on the frontend.

**Comment by bakeiro** [comment]
Hi!
I started a discussion here and seems that isn't a good solution... I will leave it here in case it's useful for others who visit this threat :)
https://github.com/ethers-io/ethers.js/discussions/3191

still, thanks for the support!
