### ISSUE TITLE
wagmi-xyz.vercel.app shows 404

### ISSUE THREAD

**Issue by Omar-Aziz** [tmm/wagmi#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

the official listed website shows 404: https://wagmi-xyz.vercel.app
![IMG_9053 2](https://user-images.githubusercontent.com/23618431/153322978-5cd554f6-efeb-4512-8fc2-77ee9579c530.jpg)

### Expected Behavior

should not 404

### Steps To Reproduce

visit https://wagmi-xyz.vercel.app/

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wagmi-xyz.vercel.app/

**Comment by tmm** [comment]
Thanks for reporting! Back up with a new design!
