### ISSUE TITLE
[bug] Unable to fetch the localhost hardhat balance

### ISSUE THREAD

**Issue by liho00** [tmm/wagmi#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.12

### Current Behavior

```
const connectors = ({ chainId }) => {
  const rpcUrl = chain.hardhat.rpcUrls[0];

  // console.log("rpcUrl", rpcUrl, developmentChains, chain.hardhat);
  return [
    new InjectedConnector({
      chains: [chain.hardhat],
      options: { shimDisconnect: true },
    }),
  ];
};
```

I am trying to get my hardhat localhost balance, but instead the browser requesting to mainnet.infura?

### Expected Behavior

it should return the balance of my current selected network balance... and provide a way set a default network.

### Steps To Reproduce

```
const connectors = ({ chainId }) => {
  const rpcUrl = chain.hardhat.rpcUrls[0];

  // console.log("rpcUrl", rpcUrl, developmentChains, chain.hardhat);
  return [
    new InjectedConnector({
      chains: [chain.hardhat],
      options: { shimDisconnect: true },
    }),
  ];
};
```

```
  const [{ data: accountData }, disconnect] = useAccount({
    fetchEns: true,
  });
  console.log("accountData?.address", accountData?.address);

  const [
    { data: balanceData, error: balanceError, loading: loadingBalance },
    getBalance,
  ] = useBalance({
    addressOrName: accountData?.address,
    // watch: true,
  });

```

### Anything else?

<img width="789" alt="image" src="https://user-images.githubusercontent.com/77238199/154783622-edd12a8b-3675-4422-b5d2-8f2f8c53f787.png">
<img width="370" alt="image" src="https://user-images.githubusercontent.com/77238199/154783629-c96187f1-d208-4d03-94ff-04dace35643c.png">

<img width="790" alt="image" src="https://user-images.githubusercontent.com/77238199/154783651-766ff477-c652-4045-bbe7-16c3fa6f7b6b.png">

<img width="790" alt="image" src="https://user-images.githubusercontent.com/77238199/154783648-00b1e2ef-0ccf-40a1-af3e-8ee42a66cb5c.png">

**Comment by tmm** [comment]
Are you passing an ethers.js provider? You need to make the provider chain-aware:

```tsx
import { providers } from 'ethers'
import { chain, WagmiProvider } from 'wagmi'

const getProvider = ({ chainId }) => {
  // Use JsonRpcProvider for hardhat
  if (chainId === chain.hardhat.id) return new providers.JsonRpcProvider()
  return new providers.AlchemyProvider(chainId)
}

export const App = ({ children }) => {
  <WagmiProvider provider={getProvider}>
    {children}
  </WagmiProvider>
}
```

**Comment by liho00** [comment]
> 

Its works, it was my bad, because i did not fully understand hardhat is a provider.
