### ISSUE TITLE
[bug] Cannot find module @walletconnect/ethereum-provider when in node context

### ISSUE THREAD

**Issue by sammdec** [tmm/wagmi#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.15

### Current Behavior

When building a page with next.js using getStaticProps, it attempts to use the commonjs module version of wagmi and breaks as it looks like wagmi-core doesnt export or include the required module.
![image](https://user-images.githubusercontent.com/878503/155216813-dcf7911c-ceb4-421c-af85-1c20cb9171e5.png)

### Steps To Reproduce

Create a next.js app
Use get static props to force serverside build of the page.
Attempt to load the page

**Comment by melissafzhang** [comment]
We are also seeing this error in nextjs!

**Comment by tmm** [comment]
What version of Next.js are you using?

I'm not able to reproduce with this [CodeSandbox](https://codesandbox.io/s/beautiful-wright-9dzkzl). Feel free to tweak it.

**Comment by sammdec** [comment]
Does code sandbox support getStaticProps?

**Comment by tmm** [comment]
You can export as zip and build/run locally.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/6759464/155815897-0da089c2-7919-4846-88be-84bc1aecf875.png">

What version of Next.js are you using? Definitely down to look into more if there's a good way to reproduce.

**Comment by sammdec** [comment]
Using v12.1 Nextjs

**Comment by sammdec** [comment]
Closing this as it seems to have resolved itself with the newer versions. I think it may have been related to a underlying library
