### ISSUE TITLE
[bug] WalletConnect + MetaMask does not reconnect on page refresh

### ISSUE THREAD

**Issue by javamonn** [tmm/wagmi#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.9

### Current Behavior

When using the `autoConnect` prop on the Provider, if a user connects via Wallet Connect using MetaMask (I did not test other Wallet Connect clients) and refreshes the page, the user appears connected from the perspective of wagmi (`useAccount`) returns an address, but actions involving the user's wallet will fail. Specifically, prompting a signature with `useSignMessage` seems to send a message across the Wallet Connect bridge and displays within the user's wallet, but never resolves in wagmi. Prompting a transaction with `useTransaction` calcuates gas, but does not display the transaction within the user's wallet.

### Expected Behavior

After connecting via Wallet Connect and refreshing the page, the user remains connected and is able to complete actions with their wallet.

### Steps To Reproduce

1. Connect using Wallet Connect
2. Refresh the page, have `autoConnect` set on wagmi provider
3. Attempt to use `useTransaction` or `useSignMessage`

**Comment by tmm** [comment]
Was able to confirm this issue using the demo in the [Sign Message](https://wagmi-xyz.vercel.app/guides/sign-message) guide. This doesn't happen with the MM or WalletLink connectors.

Seems related to this https://github.com/WalletConnect/walletconnect-monorepo/issues/718

**Comment by javamonn** [comment]
Agree that the issue on walletconnect looks to be the cause, thanks for flagging that. Not sure if you want to close this in favor of the upstream issue or leave this open to track.
