### ISSUE TITLE
Module parse failed: Unexpected token (255:5)

### ISSUE THREAD

**Issue by wnz99** [tmm/wagmi#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

Module parse failed: Unexpected token (255:5)

### Current Behavior

CRA with package `react-scripts@4.0.3` fails with this error:

```
./node_modules/wagmi-core/dist/wagmi-core.esm.js 255:5
Module parse failed: Unexpected token (255:5)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| class InjectedConnector extends Connector {
>   id = 'injected';
|   ready = typeof window != 'undefined' && !!window.ethereum;
|   #provider;

```

`wgami` versions below `0.2.15` work fine.

### Expected Behavior

`react-scripts@4.0.3` should still be supported.

### Steps To Reproduce

* Boostrap CRA project
* Add `react-scripts@4.0.3` and `wagmi@0.2.15`

**Comment by jamal-jackson** [comment]
I'm experiencing this issue as well from webpack in storybook.

**Comment by SonnyCastro** [comment]
Having this same issue :(

**Comment by tmm** [comment]
@SonnyCastro happy to look into it if you have a minimal reproducible example!

**Comment by SonnyCastro** [comment]
> @SonnyCastro happy to look into it if you have a minimal reproducible example!

I fixed the issue by editing the browsersList within package.json

Video of solution: https://www.youtube.com/watch?v=tFqj-JKYr4M

BTW the wagmi library is great! Thank you for creating and maintaining it. It makes a lot of dev's life's easier.

You're a beast and congrats for making such a sick lib! 👏👊🔥

**Comment by yusuf8ahmed** [comment]
@SonnyCastro , i just stumbled into this error but after watching the video I ran into this error also:

```
./node_modules/wagmi-core/dist/wagmi-core.esm.js
SyntaxError: ~/client/node_modules/wagmi-core/dist/wagmi-core.esm.js: Missing class properties transform.
  257 | const shimKey = 'wagmi.shimDisconnect';
  258 | class InjectedConnector extends Connector {
> 259 |   id = 'injected';
      |   ^^^^^^^^^^^^^^^^
  260 |   ready = typeof window != 'undefined' && !!window.ethereum;
  261 |   #provider;
  262 |

```

**Comment by yusuf8ahmed** [comment]
> > @SonnyCastro happy to look into it if you have a minimal reproducible example!
> 
> I fixed the issue by editing the browsersList within package.json
> 
> Video of solution: https://www.youtube.com/watch?v=tFqj-JKYr4M
> 
> BTW the wagmi library is great! Thank you for creating and maintaining it. It makes a lot of dev's life's easier.
> 
> You're a beast and congrats for making such a sick lib! 👏👊🔥



> > @SonnyCastro happy to look into it if you have a minimal reproducible example!
> 
> I fixed the issue by editing the browsersList within package.json
> 
> Video of solution: https://www.youtube.com/watch?v=tFqj-JKYr4M
> 
> BTW the wagmi library is great! Thank you for creating and maintaining it. It makes a lot of dev's life's easier.
> 
> You're a beast and congrats for making such a sick lib! 👏👊🔥

@SonnyCastro , i just stumbled into this error but after watching the video I ran into this error also:

```
./node_modules/wagmi-core/dist/wagmi-core.esm.js
SyntaxError: ~/client/node_modules/wagmi-core/dist/wagmi-core.esm.js: Missing class properties transform.
  257 | const shimKey = 'wagmi.shimDisconnect';
  258 | class InjectedConnector extends Connector {
> 259 |   id = 'injected';
      |   ^^^^^^^^^^^^^^^^
  260 |   ready = typeof window != 'undefined' && !!window.ethereum;
  261 |   #provider;
  262 |

```

**Comment by yusuf8ahmed** [comment]
@SonnyCastro , i just stumbled into this error but after watching the video I ran into this error also:

```
./node_modules/wagmi-core/dist/wagmi-core.esm.js
SyntaxError: ~/client/node_modules/wagmi-core/dist/wagmi-core.esm.js: Missing class properties transform.
  257 | const shimKey = 'wagmi.shimDisconnect';
  258 | class InjectedConnector extends Connector {
> 259 |   id = 'injected';
      |   ^^^^^^^^^^^^^^^^
  260 |   ready = typeof window != 'undefined' && !!window.ethereum;
  261 |   #provider;
  262 |

```

**Comment by zfogg** [comment]
+1

**Comment by SonnyCastro** [comment]
> @SonnyCastro and @tmm , i just stumbled into this error but after watching the video I ran into this error also any guess on how to fix it?
> 
> ```
> ./node_modules/wagmi-core/dist/wagmi-core.esm.js
> SyntaxError: ~/client/node_modules/wagmi-core/dist/wagmi-core.esm.js: Missing class properties transform.
>   257 | const shimKey = 'wagmi.shimDisconnect';
>   258 | class InjectedConnector extends Connector {
> > 259 |   id = 'injected';
>       |   ^^^^^^^^^^^^^^^^
>   260 |   ready = typeof window != 'undefined' && !!window.ethereum;
>   261 |   #provider;
>   262 |
> ```

Hey Yusuf i had that exact same error and was able to resolve it with this video solution: [https://www.youtube.com/watch?v=tFqj-JKYr4M](url)

Im not sure what else to do if that doesn't resolve your issue only thing that come to mind is upgrading create-react-app version 🤷🏽‍♂️

**Comment by thomasamlee** [comment]
Try adding `presets: [['@babel/preset-env', { targets: { esmodules: true } }]],` to your babel presets exactly like how wagmi is configured: https://github.com/tmm/wagmi/blob/main/babel.config.js

**Comment by tmm** [comment]
Fix https://github.com/tmm/wagmi/pull/289
