### ISSUE TITLE
[bug] useContractWrite not using args

### ISSUE THREAD

**Issue by zkSoju** [tmm/wagmi#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.18

### Current Behavior

When running `editSwap` with the following code

``` typescript
  const [{ data: editData, error: editError, loading: editLoading }, editSwap] =
    useContractWrite(
      {
        addressOrName: genStore.currentContract,
        contractInterface: contractInterface,
      },
      "extendAllotedTime",
      { args: [0] }
    );
```

I get the following error:

```
Error: missing argument: passed to contract (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=contracts/5.5.0)
```

I tried placing the argument with and without an array and successfully used useContractWrite on other functions with no args.

**Comment by tmm** [comment]
Thanks for reporting. Looks like the issue is because `0` evaluates to `false` [here](https://github.com/tmm/wagmi/blob/main/packages/react/src/hooks/contracts/useContractWrite.ts#L57). This should be updated to explicitly check for `undefined`/`null`.

**Comment by tmm** [comment]
Good to know. Will take a look.

**Comment by zkSoju** [comment]
Judging by the code I still can't figure out why `[number]` or `number` isn't being passed in as an argument.
