### ISSUE TITLE
[bug]When clicking on MetaMask to connect your wallet the Coinbase browser extension also pops up

### ISSUE THREAD

**Issue by SonnyCastro** [tmm/wagmi#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.2.17

### Current Behavior

When clicking on MetaMask to connect your wallet the Coinbase browser extension also pops up.
If you have the CoinBase wallet extension downloaded just like MetaMask it opens up when you click on MetaMask as your chosen provider for connection. However, when you click on CoinBase as your chosen wallet provider MetaMask doesn't open up as it should. So the problem is only when you click on MetaMask the CoinBase wallet extension pops up when it shouldn't because I clicked on MetaMask, not CoinBase. 

I first noticed this within my app but then went back to docs to see if I was missing something but noticed it also happens within the docs in the connect wallet guide section (https://wagmi.sh/guides/connect-wallet).

### Expected Behavior

The expected behavior should be when I click on MetaMask to connect my wallet only the MetaMask extension should popup and not any other wallet provider extension.

### Steps To Reproduce

Download the CoinBase wallet extension got to the docs here : [https://wagmi.sh/guides/connect-wallet](url)
Click on MetaMask then watch both MetaMask and CoinBase wallet extension pop up

CoinBase Extension Download [https://chrome.google.com/webstore/detail/coinbase-wallet-extension/hnfanknocfeofbddgcijnmhnfnkdnaad?hl=en](url)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wagmi.sh/guides/connect-wallet

### Anything else?

Browser: Google Chrome Version 99.0.4844.74 (Official Build) (x86_64)
MetaMask Version: 10.11.1
CoinBase Version: 2.10.3
WAGMI Version: ^0.2.17

**Comment by tmm** [comment]
This is a limitation of injected wallets. There's not way to differentiate which injected wallet you are making a request to.

**Comment by SonnyCastro** [comment]
> This is a limitation of injected wallets. There's not way to differentiate which injected wallet you are making a request to.

Thanks for the feedback yea I figured this also as I see the problem with all dapp's.

**Comment by adbario** [comment]
@tmm @SonnyCastro There is actually a way to differentiate at least MetaMask and Coinbase Wallet.

If only MetaMask is installed, you normally use `window.ethereum` as a provider. If there's also Coinbase wallet installed same time, using the usual `window.ethereum` will open both as mentioned above. But in this case, there's also `window.ethereum.providers` which is an array of providers and you can find the correct one for MetaMask only by looping the array and checking which item has `isMetaMask` property.

So to prepare for having both wallet extensions installed, for Coinbase use all the usual methods but for MetaMask first check if the `providers` array exists and if yes, find the right one there.

I can look into making a PR for this, if you're keen to have an additional connector that guarantees that only MetaMask will be opened.

**Comment by adbario** [comment]
> @adbario interesting! thanks dropping the knowledge.

No problem at all.

Here's a quick example that I've used before to make sure only MetaMask fires up, in case someone want's to play around with the idea.

```javascript
function getProvider() {
  const { ethereum } = window as any;

  if (ethereum?.isMetaMask) {
    if (ethereum?.providers) {
      return ethereum.providers.find(
        (provider: InjectedProvider) => provider.isMetaMask
      );
    }

    return ethereum;
  }
}
```
