### ISSUE TITLE
[bug] Attempting to connect to Coinbase Wallet leads to "Buffer is not defined" error

### ISSUE THREAD

**Issue by kbanta11** [tmm/wagmi#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.21

### Current Behavior

When I try to connect to coinbase wallet, the modal for Coinbase Wallet correctly opens up, but throws the following error (which stalls the web app). It seems to be related to the QR code they try to show.

```
Uncaught ReferenceError: Buffer is not defined
    at Object.__ (QRCode.js:28:1)
    at j (index.js:368:1)
    at Array.forEach (<anonymous>)
    at preact__WEBPACK_IMPORTED_MODULE_0__.options.__r (index.js:36:1)
    at j (index.js:171:1)
    at w (children.js:137:1)
    at L (index.js:392:1)
    at j (index.js:224:1)
    at w (children.js:137:1)
    at L (index.js:392:1)
```

### Expected Behavior

To be able to connect to coinbase wallet.

### Steps To Reproduce

I tried following both the set up guide from both Wagmi and Coinbase (https://docs.cloud.coinbase.com/wallet-sdk/docs/wagmi#additional-resources), including trying their troubleshooting solution at the bottom of the page.

### Anything else?

I've tried copying my package list into the working codesandbox example (that does work), but it doesn't seem to break when I do this, so I'm at a loss for what is causing my issue. I'm also unable to get WalletConnect to open on my machine but can in CodeSandbox, so is this maybe expected that these connections will not work when running from localhost or something?

**Comment by codingwithmanny** [comment]
@kbanta11 what are you using as your base?

- Create React App
- ViteJS React
- NextJS
- GatsbyJS

**Comment by kbanta11** [comment]
I used Create React App to spin it up initially

**Comment by tmm** [comment]
@kbanta11 check this out: https://github.com/tmm/wagmi/issues/270#issuecomment-1075473815
