### ISSUE TITLE
[bug] useAccount "loading" should reflect ENS lookup from first render

### ISSUE THREAD

**Issue by davisshaver** [tmm/wagmi#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.21

### Current Behavior

With a hook call such as `const [{ data , loading }] = useAccount({ fetchEns: true });`, the value for `loading` will be false during initial render as the initial state for `useEnsLookup` is `{ loading: false }`. This introduces a need for application developers to track load status until "second load" to ensure that ENS lookup has been performed.

### Expected Behavior

The initial state for `useEnsLookup` should reflect the `fetchEns` parameter. If `fetchEns` is true, the initial state for `useEnsLookup` should be `{ loading: true }`. This will allow applications to withhold actions through initial account connection until ENS data has been fetched.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/dazzling-wright-4405hb?file=/src/App.tsx:0-32

**Comment by montanaflynn** [comment]
Yeah I get the address then the actual ENS address.

**Comment by tmm** [comment]
See https://github.com/tmm/wagmi/pull/264#issuecomment-1088091028 for more info
