### ISSUE TITLE
[bug] Default Remix Example Errors Out

### ISSUE THREAD

**Issue by rosman83** [tmm/wagmi#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.21

### Current Behavior

I have cloned the repo of the remix example merged into wagmi over at a `examples/remix` - Upon installing the dependencies and making no changes beside configuring the ENV file - starting the app with `npm run dev` leads to an application error on the root with the following error.

```
TypeError: Cannot read properties of undefined (reading 'root')
```

How can we fix this official example so that we can start using wagmi with Remix?

### Expected Behavior

The expected behavior is to compile without error on a clone.

### Steps To Reproduce

1. Clone the `examples/remix` example in the `tmm/wagmi` repo.
2. run `npm install && npm run dev`
3. Error will be displayed.

**Comment by tmm** [comment]
When the dependencies were installed, did [these packages get patched](https://github.com/tmm/wagmi/tree/main/examples/remix/patches)?

**Comment by rosman83** [comment]
Here is the output of `npm install`:

```
> postinstall
> patch-package && remix setup node

patch-package 6.4.7
Applying patches...
Unrecognized patch file in patches directory safe-event-emitter_1.0.1.patch

**ERROR** Failed to apply patch for package @remix-run/dev at path

    node_modules/@remix-run/dev

  This error was caused because @remix-run/dev has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run

    patch-package @remix-run/dev

  Info:
    Patch file: patches/@remix-run+dev+1.1.1.patch
    Patch was made for version: 1.1.1
    Installed version: 1.3.2

---
patch-package finished with 1 warning(s), 1 error(s).
Successfully setup Remix for node.
```

**Comment by rosman83** [comment]
Seems the issue was needing to also configure the version in the patch files - I will try this now and close if successful

**Comment by rosman83** [comment]
Hmm - althought the safe event emitter patches correctly - I am still experiencing errors in the patch process for remix run 

```
**ERROR** Failed to apply patch for package @remix-run/dev at path

    node_modules/@remix-run/dev

  This error was caused because patch-package cannot apply the following patch file:

    patches/@remix-run+dev+1.3.2.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:

    patch-package @remix-run/dev
```
