### ISSUE TITLE
[bug] First Mainnet/Testnet Switch causes MM to Disconnect

### ISSUE THREAD

**Issue by Pczek** [tmm/wagmi#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.21

### Current Behavior

When switching from BSC Mainnet to BSC Testnet for the first time, when not 'autoconnected' it will disconnect metamask without any error.
Not sure why this happens. I first commented here as it seemed related able. 
https://github.com/tmm/wagmi/issues/180#issuecomment-1077705039

![demo](https://user-images.githubusercontent.com/839848/160402474-26a53f10-7193-4f22-9656-fcf5d0ad9a4b.gif)

### Expected Behavior

Metamask should stay connected during network switch.

### Steps To Reproduce

+ don't use autoconnect in Provider Code
+ use Metamask
+ Start from a fresh page (only seems to be reproducible on the first change)
+ switch from BSC Mainnet to BSC Testnet
+ check connection status of metamask

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-issue-287-9o9cos

### Anything else?

This Error bubbles up in our Dapp if this behaviour occurs., but can't see it in the CodeSandbox. 
Not sure where this is coming from. Can't find the source. Might be related.

```
Error: underlying network changed (
  event="changed", 
  network={"name":"bnb","chainId":56,"ensAddress":null,"_defaultProvider":null}, 
  detectedNetwork={"name":"bnbt","chainId":97,"ensAddress":null,"_defaultProvider":null},
  code=NETWORK_ERROR, 
  version=providers/5.6.1
)
    at Logger.makeError (index.js?dd68:219:1)
    at Web3Provider.eval (base-provider.js?4ba1:971:1)
    at Generator.next (<anonymous>)
    at fulfilled (base-provider.js?4ba1:5:43)
```

**Comment by tmm** [comment]
Seems related to https://github.com/tmm/wagmi/issues/180#issuecomment-1077705039. Will investigate further.

**Comment by tmm** [comment]
Confirmed this is an issue with MM (not WalletConnect or Coinbase Wallet). Going to look into it more.

Here's the MM issue: https://github.com/MetaMask/metamask-extension/issues/13375

**Comment by tmm** [comment]
Closing this issue as this is a problem with MetaMask (linked above).
