### ISSUE TITLE
[bug] iOS Safari <= 14.4 doesnt support private class instance fields 

### ISSUE THREAD

**Issue by sammdec** [tmm/wagmi#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

wagmie-core 0.1.15

### Current Behavior

Safari iOS doesnt support private instance fields in a class, this causes an exception on devices due to the `#` character. 

### Expected Behavior

Ideally it would be transpiled and targeted at a lower version

**Comment by csadai** [comment]
+1 for the issue detection (I have the same one on Safari 14.2) and for the simple solution proposed.

**Comment by sammdec** [comment]
@tmm we might have to open this up it doesnt look like the update to the tsconfig worked

**Comment by tmm** [comment]
This should do it! Tested out with iOS 14.1 in the simulator.

https://github.com/tmm/wagmi/pull/292

**Comment by csadai** [comment]
#292 fixes it for me. Thank you @tmm you're awesome 🎊

**Comment by sammdec** [comment]
I tested it with `targets: "defaults, not ie 11"`, that seemed to help alot
