### ISSUE TITLE
[bug] react 18 not supported

### ISSUE THREAD

**Issue by abcoathup** [tmm/wagmi#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.24

### Current Behavior

Using latest version of React (18)
```
$ npx create-react-app my-app
```

Appears not be supported
```
$ npm add wagmi ethers
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from wagmi@0.2.24
npm ERR! node_modules/wagmi
npm ERR!   wagmi@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Dhaiwat10** [comment]
Also getting the `Hydration failed because the initial UI does not match what was rendered on the server` error when using `wagmi` with React 18 and Next.js

**Comment by adbario** [comment]
React 18 was just released, please give the open-source devs some time and you're also very welcome to contribute with pull requests.

**Comment by Dhaiwat10** [comment]
@adbario of course! Just reporting the error, no demands :)

**Comment by cesargdm** [comment]
I'm using react 18 with vite and the library works for me :D
