### ISSUE TITLE
[bug] Two Wallet Connection Modal

### ISSUE THREAD

**Issue by DaniyarSarasenov** [tmm/wagmi#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.25

### Current Behavior

I am using the package in my next.js application.
There are two wallet connection in my chrome browser. Metamask and Coinbase
When I press the metamask connection, both of them shows at the same time.

https://wagmi.sh/guides/connect-wallet
in this link, just also found same issue.

**Comment by tmm** [comment]
This is a problem with Injected wallets in general. See https://github.com/tmm/wagmi/pull/279 and https://github.com/tmm/wagmi/issues/260 for more info

This particular issue could be solved with a `MetaMaskConnector`, but it won't prevent other Injected wallet conflicts (Tally v Frame, Frame v Coinbase Wallet, etc).

**Comment by adbario** [comment]
Yes as @tmm said, most of the browser extension wallets are using the same Ethereum provider that gets plugged into the browser window.

Ideally, you should have only one of these kinds of wallet extensions installed, use different browsers for different wallets, just close the wallets you don't want to use each time or try to better detect which wallet is intended to be used.

https://github.com/tmm/wagmi/pull/279 is for making sure only MetaMask will be fired. Sadly the same kind of detection isn't possible for some wallets when there are multiple ones installed at the same time. I managed to get [Tally](https://tally.cash/) and [XDEFI](https://www.xdefi.io/) detected though, but no luck with [Frame](https://frame.sh/) if MetaMask is installed same time.
