### ISSUE TITLE
[bug] WalletConnect causes 500 Internal Server Error in NextJS production

### ISSUE THREAD

**Issue by Sam-Scolari** [tmm/wagmi#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.26

### Current Behavior

I am using wagmi in a NextJS project hosted on Vercel. When I run the app in dev mode all 3 connectors work fine (Injected, Coinbase, and WalletConnect), but when I build the app for production I am given a 500 Internal Server error unless I comment out the WalletConnectConnector portion. Both Injected and Coinbase wallet function normally in production.

**Comment by AmagiDDmxh** [comment]
My guess is that has something to do with init config when doing `new WalletConnector({ ..., infuraId: ...  }` 

you're probably missing the `infuraId`

**Comment by tmm** [comment]
@Sam-Scolari please provide a minimal reproducible example (link to GH repo, CodeSandbox, etc.) and re-open

@AmagiDDmxh 's suggestion also looks like a good one.

**Comment by Sam-Scolari** [comment]
InfuraId was included but the issue was resolved when I updated to 0.2.28. Thanks.
