### ISSUE TITLE
[bug] Typescript error makes build to fail

### ISSUE THREAD

**Issue by cesargdm** [tmm/wagmi#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.26

### Current Behavior

When building my project based on Vite, the first steps which simply runs `tsc`, TypeScript throws the next error. But if `WalletLinkConnector` is not used the error does not occur.

**Subsequent property declarations must have the same type.**

```bash
node_modules/.pnpm/walletlink@2.5.0/node_modules/walletlink/dist/index.d.ts:10:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'ethereum' must be of type '(InjectedProviders & { on?: ((...args: any[]) => void) | undefined; removeListener?: ((...args: any[]) => void) | undefined; request<T = any>(args: RequestArguments): Promise<...>; }) | undefined', but here has type 'WalletLinkProvider | undefined'.

10         ethereum?: WalletLinkProvider;
           ~~~~~~~~

  node_modules/.pnpm/wagmi-core@0.1.20_7cf8998ad3c2040bdf49599dfb442f59/node_modules/wagmi-core/dist/declarations/src/types/index.d.ts:74:9
    74         ethereum?: InjectedProviders & {
               ~~~~~~~~
    'ethereum' was also declared here.


Found 1 error in node_modules/.pnpm/walletlink@2.5.0/node_modules/walletlink/dist/index.d.ts:10
```

<img width="1326" alt="Screen Shot 2022-04-17 at 10 59 16 AM" src="https://user-images.githubusercontent.com/10179494/163722531-73e7edbb-883d-418c-ad53-6dd9346fe64d.png">

### Expected Behavior

The project should build without any type errors

### Steps To Reproduce

If the `WalletLinkConnector` is added to the list of connectors running `tsc` on a typescript project fails (or at least with Vite).

### Anything else?

I believe it has to do with a double global declaration of `window.ethereum`

<img width="1288" alt="Screen Shot 2022-04-17 at 10 57 38 AM" src="https://user-images.githubusercontent.com/10179494/163722440-f8950314-fd45-49d9-aea2-1e1b5e052256.png">

**Comment by tmm** [comment]
@cesargdm can you add `skipLibCheck: true` to your `tsconfig.json`?

**Comment by codingwithmanny** [comment]
Had this same issue, but yeah like @tmm mentioned that should fix things.

**Comment by cesargdm** [comment]
@tmm thank you!
