### ISSUE TITLE
[issue] InjectedConnector always opens the injected (MetaMask) prompt

### ISSUE THREAD

**Issue by marvinkennis** [tmm/wagmi#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.0

### Current Behavior

Whenever an Injected connector is initiated and found, the connection prompt (in my case MetaMask) is always initiated, asking me which MetaMask account I want to connect with. From a UX perspective, it would be nicer to wait until the user clicks one of the wallet buttons to trigger this. I've essentially copied the code from the example docs.

### Expected Behavior

Wait for the connection to be initiated by the user, or have an option to toggle this off. I checked the source, seems like getAccounts() is called when an InjectedConnector is initiated, which in turn triggers a window.ethereum.requestAccounts() call.

**Comment by iDuuck** [comment]
This sounds like you are using the [`autoConnect` option](https://wagmi-xyz.vercel.app/docs/provider#autoconnect-optional) of the `Provider` component? Can you confirm? If not, could you please create a small reproduction (i.e. CodePen)?

**Comment by marvinkennis** [comment]
Absolutely correct, apologies for missing that. All good now.

**Comment by marvinkennis** [comment]
Sorry, gotta reopen this one. I thought it was fixed, but it only seemed that way as it kept the MetaMask connection (clicking on Connect with MetaMask would instantly show the wallet address). 

I am no longer using autoConnect
`<Provider connectors={connectors}>`

Steps to reproduce:
- Sign in with MetaMask
- Disconnect from MetaMask using the Connected Sites options
- Reload the page

**Comment by marvinkennis** [comment]
Sorry, gotta reopen this one. I thought it was fixed, but it only seemed that way as it kept the MetaMask connection (clicking on Connect with MetaMask would instantly show the wallet address). 

I am no longer using autoConnect
`<Provider connectors={connectors}>`

Steps to reproduce:
- Sign in with MetaMask
- Disconnect from MetaMask using the Connected Sites options
- Reload the page
