### ISSUE TITLE
[bug] MetaMask connector opens both MetaMask and Coinbase Wallet modals

### ISSUE THREAD

**Issue by vubui** [tmm/wagmi#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.28

### Current Behavior

https://user-images.githubusercontent.com/1538687/164948227-b637a2df-483f-4665-85c1-238bcd5075be.mp4

`connect(metamaskConnector)` opens both MetaMask and Coinbase

### Expected Behavior

Button to open MetaMask extension should open just MetaMask

### Steps To Reproduce

1. Go to https://wagmi.sh/guides/connect-wallet
2. Tap MetaMask

**Comment by tmm** [comment]
See https://github.com/tmm/wagmi/issues/260
