### ISSUE TITLE
[bug] WalletConnect mobile view shows qr code instead of deeplink buttons

### ISSUE THREAD

**Issue by angelagilhotra** [tmm/wagmi#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.28

### Current Behavior

When initiating connectors 
```
export const connectors = () => [
  new InjectedConnector({ chains }),
  new WalletConnectConnector({
    chains,
    options: {
      infuraId,
      qrcode: true,
    },
  }),
];
```
and setting `qrcode: true`, it works correctly on desktop -- displays the qr code but I'm assuming this should handle the display of deeplinks to mobile wallets on mobile version of the website, but it doesn't. 

### Expected Behavior

When the modal is triggered on mobile, display deeplinks to various wallets instead of the qr code.

### Steps To Reproduce

- initialise the wagmi provider with walletconnect

**Comment by nickbytes** [comment]
Here's link to 0.2.x docs: https://0.2.x.wagmi.sh

Here's my example on an iPhone 11 https://user-images.githubusercontent.com/3009331/165353118-87e1dd12-386c-4335-94ac-ec16e6905d0a.MOV

Walletconnect does some device detection, so there's a chance could just not be picking up your specific device?

**Comment by tmm** [comment]
@angelagilhotra feel free to re-open with more info. I'm not able to reproduce either.

**Comment by r29taheri** [comment]
Having the same issue,
Package Version
0.4.3

Also tested on [0.4.x example](https://0.4.x.wagmi.sh/examples/connect-wallet) and [latest version example](https://wagmi.sh/examples/connect-wallet)
on most devices works fine but on some iPhone devices shows only Qr option.
what it shows:
![image](https://user-images.githubusercontent.com/24974629/178106859-0dedf36b-56f3-43a4-b271-92572ab75345.png)
expected result:
![image](https://user-images.githubusercontent.com/24974629/178106874-8108a293-ed6d-4b97-804a-efed0392ab91.png)
