### ISSUE TITLE
[bug] ConnectorAlreadyConnectedError: Connector already connected

### ISSUE THREAD

**Issue by thecooltechguy** [tmm/wagmi#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.0

### Current Behavior

I created a new next.js react app and I installed wagmi and tried to use the quickstart code on the front page of https://wagmi.sh/, but I keep getting the following error when I click my "Connect wallet" button (which then calls the `connect` function from the `useConnect()` hook):

```ConnectorAlreadyConnectedError: Connector already connected```

Investigating further, I'm finding that the output of `useAccount()` looks something like the following:
```{ data: null, error: null, fetchStatus: "idle", isError: false, isFetched: true, isFetching: false, isIdle: false, isLoading: false, isRefetching: false, isSuccess: true, refetch: refetch(), … }```

The interesting thing to note here is that `isSuccess` is `true`, while `data` is `null`.

I'm using Metamask on Firefox (which is connected to a local Ganache blockchain running on my laptop). I tried switching networks within Metamask and also restarting my browser, but none of these options worked.

### Expected Behavior

Calling the `connect` function returned by the `useConnect()` hook should return a valid, non-null `data` object, without throwing a `ConnectorAlreadyConnectedError` error.

### Steps To Reproduce

1. Go to https://codesandbox.io/s/boring-panna-id8ocn?file=/src/App.tsx
2. Open the preview in a new window
3. Click on the "Connect Wallet" button
4. Nothing will happen
5. Open up the console and you will see an error: "ConnectorAlreadyConnectedError"

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/boring-panna-id8ocn?file=/src/App.tsx

### Anything else?

Thanks for making this AWESOME library! 🔥 🔥

**Comment by tmm** [comment]
Example in the docs was broken. The following does not work because `React.MouseEvent` is passed implicitly to `connect`.

```tsx
<button onClick={connect}>Connect Wallet</button>
```

Should be the following instead:

```tsx
<button onClick={() => connect()}>Connect Wallet</button>
```
