### ISSUE TITLE
[bug] Error after update to 0.3.1

### ISSUE THREAD

**Issue by bryantoh** [tmm/wagmi#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.1

### Current Behavior

Show below error after update wage 0.3.1 and cause my application not able to start

![image](https://user-images.githubusercontent.com/37606508/165883432-f6f5edbb-7aff-47d3-bf3d-c73dd14ed481.png)

**Comment by tmm** [comment]
What bundler are you using? Can you provide a reproducible example.

**Comment by bryantoh** [comment]
what do you mean by which bundler? basically I just update to 0.3.1 and start my application and it show above error.

**Comment by tmm** [comment]
Are you using a tool, like Vite, Webpack, Parcel, Next.js, CRA, etc.?

A reproducible example will help us solve your issue faster and not waste time that could be spent on other things.

**Comment by bryantoh** [comment]
this is the error I'm facing now after did NPM UPDATE

![image](https://user-images.githubusercontent.com/37606508/165886105-fe2e10e9-6d51-41ce-b5e2-69eb52a0842c.png)

**Comment by cannc4** [comment]
Getting this in next with latest 
```
react.development.js?dd75:1632 Uncaught TypeError: Cannot read properties of null (reading 'useEffect')
    at Object.useEffect (react.development.js?dd75:1632:1)
    at Provider (wagmi.esm.js?dce6:198:3)
    ```

**Comment by wong2** [comment]
Can you answer @tmm 's question? That will help solve your problem faster.

**Comment by bryantoh** [comment]
> Are you using a tool, like Vite, Webpack, Parcel, Next.js, CRA, etc.?
> 
> A reproducible example will help us solve your issue faster and not waste time that could be spent on other things.

Im using Create React App.

**Comment by jxom** [comment]
@bryantoh – I don't seem to run into this issue when setting up a fresh Create React App project. Can you please upload a reproducible example? Thanks.

**Comment by bryantoh** [comment]
I created a new CRA project, and below is the error...

![image](https://user-images.githubusercontent.com/37606508/165908273-3bd71d7e-a2a6-46be-9297-20cd929b82d3.png)

**Comment by bryantoh** [comment]
@tmm , @jxom , I tried to clean-install and using wagmi@0.3.0, it show below warning:

![image](https://user-images.githubusercontent.com/37606508/165933354-f87eb7ff-3f53-4206-9669-fe393e0eaa0e.png)

when I started the application using "npm start", it throw below error. Hope it help. 

![image](https://user-images.githubusercontent.com/37606508/165933531-c980baf3-45a5-443f-852e-1fcdc40ddcf4.png)

**Comment by outdoteth** [comment]
Try upgrading your node version to 16

**Comment by tmm** [comment]
@bryantoh can you give @jxom and me access to the code or post a link to the source? Neither of us have been able to reproduce.

**Comment by davidlee1435** [comment]
+1- also having this issue:

```
- react-scripts: 4.0.3 (Webpack 4)
- react: 17.0.2
- node: 14.18.1
```

**Comment by tmm** [comment]
Here's a [minimal CRA example that works with wagmi](https://github.com/tmm/cra-wagmi). Check it out and compare the setup.

If you want us to look into the issue further, please provide a minimal example.

**Comment by bryantoh** [comment]
> Here's a [minimal CRA example that works with wagmi](https://github.com/tmm/cra-wagmi). Check it out and compare the setup.
> 
> If you want us to look into the issue further, please provide a minimal example.

I will give it a try. Did a quick comparison, I believe some dependencies are needed eg "buffer" and "events".

**Comment by bryantoh** [comment]
> +1- also having this issue:
> 
> ```
> - react-scripts: 4.0.3 (Webpack 4)
> - react: 17.0.2
> - node: 14.18.1
> ```

Initially I was using the same setup, but having this issue. After upgrade node and react still same problem.

**Comment by davidlee1435** [comment]
The issue is `react-scripts@4.0.3`- when I downgrade the minimal example that @tmm linked to version 4.0.3, I could reproduce the issue.

**Comment by jxom** [comment]
You may need to update to `react-scripts@^5`
