### ISSUE TITLE
isConnecting returns true even when wallet is not connected on client-side route change (Remix)

### ISSUE THREAD

**Issue by jcheese1** [tmm/wagmi#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.0

### Current Behavior

 `isConnecting` returns true on client-side route transition, even when you don't have a wallet connected.
 
 Repro here:
 https://codesandbox.io/s/vigilant-firefly-guj5zt
 
 As you can see, isConnected becomes true on route change above

Also, when connected to a wallet, switching between pages loses the `activeConnector` field and becomes undefined for some reason. That bug can also be repro'd on the link above.
### 

### Expected Behavior

- `isConnected` remains false even after route change
- `activeConnector` to be defined on route change after wallet connection established

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/pedantic-agnesi-r8dn22

### Anything else?

isConnected bug:
https://user-images.githubusercontent.com/15570714/166090160-86c4ee0e-a3c6-4fe5-bc1f-34da25f1412c.mp4

activeConnector bug:
https://user-images.githubusercontent.com/15570714/166090161-e553db9c-0e47-4fdf-85dd-47cd22d0f917.mp4

**Comment by jxom** [comment]
@jcheese1 – you may need to memoize the `createClient` creation with `useMemo`. I have [updated the example](https://github.com/tmm/wagmi/pull/392) to reflect this.
