### ISSUE TITLE
[bug] Buffer error

### ISSUE THREAD

**Issue by bryantoh** [tmm/wagmi#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.1

### Current Behavior

Showing below error when click on the WalletConnect after upgrade to 0.3.1

![image](https://user-images.githubusercontent.com/37606508/166153462-7d718253-e6db-4711-87c9-2ce305187a81.png)

**Comment by tmm** [comment]
Some [connectors](https://github.com/coinbase/coinbase-wallet-sdk/issues/56) unfortunately require Node.js pollyfills depending on your bundler set up. In these situations, you likely need to provide the `Buffer` polyfill to the browser. Install `buffer` (`npm i buffer`) and add to the `window`.

Here's how it's done for [Vite](https://github.com/tmm/wagmi/blob/main/examples/vite-react/index.html#L14=), [Remix](https://github.com/tmm/wagmi/blob/main/examples/remix/app/entry.client.tsx#L6-L9=), and [Create React App](https://github.com/tmm/wagmi/blob/main/examples/cra/src/index.tsx#L15-L18=).

**Comment by bryantoh** [comment]
Thanks. It's working now.
