### ISSUE TITLE
[bug] Refresh browser cause previous connector connection gone

### ISSUE THREAD

**Issue by bryantoh** [tmm/wagmi#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.1

### Current Behavior

Previous was working fine. After upgrade to 0.3.1 suddenly refresh will cause connector information become "undefined" from useAccount hook. 

I have checked, the wagmi.store still storing the account data.

![image](https://user-images.githubusercontent.com/37606508/166155153-3f4106ff-783a-494e-8406-c03c6ef4ffdb.png)

**Comment by tmm** [comment]
Do you have the [`autoConnect`](https://wagmi.sh/docs/client#autoconnect-optional=) flag set to `true`? If this is not set, the wallet will not be automatically connected when the page loads. If this doesn't fix your issue, please re-open with a minimal reproducible example.

**Comment by bryantoh** [comment]
> Do you have the [`autoConnect`](https://wagmi.sh/docs/client#autoconnect-optional=) flag set to `true`? If this is not set, the wallet will not be automatically connected when the page loads. If this doesn't fix your issue, please re-open with a minimal reproducible example.


Yes already set to true. But not working.

![image](https://user-images.githubusercontent.com/37606508/166172626-c3d1128e-853a-47f0-b1cd-1c4c9d3a1fc8.png)

**Comment by bryantoh** [comment]
Below are the code. Every time I refresh, I'm not able to call mint function. When I printout the useContract hook returned object, the connector is undefined. 

`App.js`

```
function App() {

    const live = process.env.REACT_APP_LIVE === "true" ? true : false;

    // API key for Ethereum node
    // Two popular services are Infura (infura.io) and Alchemy (alchemy.com)
    //const infuraId = process.env.REACT_APP_INFURA_KEY;
    const alchemyId = process.env.REACT_APP_ALCHEMY_KEY2
    //const infuraId = process.env.INFURA_ID;
    console.log("alchemyId")
    console.log(alchemyId)

    const chains = defaultChains;
    const defaultChain = chain.mainnet;

    // polyfill Buffer for client
    if (!window.Buffer) {
        window.Buffer = Buffer
    }

    // Set up connectors
    const client = createClient({
        autoConnect: true,
        connectors({ chainId }) {
            console.log("chainId: " + chainId);
            const chain = chains.find((x) => x.id === chainId) ?? defaultChain;
            console.log("chain.Id: " + chain.id);
            console.log(chain.rpcUrls);
            console.log("chain.rpcUrls.alchemy: " + chain.rpcUrls.alchemy);
            const rpcUrl = chain.rpcUrls.alchemy
                ? `${chain.rpcUrls.alchemy}/${alchemyId}`
                : chain.rpcUrls.default

            console.log("RPCURL: " + rpcUrl)
            return [
                new InjectedConnector(),
                new CoinbaseWalletConnector({
                    options: {
                        appName: 'Abokado',
                        chainId: chain.id,
                        jsonRpcUrl: rpcUrl,
                    },
                }),
                new WalletConnectConnector({
                    options: {
                        qrcode: true,
                        rpc: {
                            [chain.id]: rpcUrl,
                        },
                    },
                }),
            ]
        },
    })


    return (
        <Provider client={client}>
            <Router>
                <ScrollToTop>
                    <Routes>
                        {live &&
                            <Route>
                                <Route index element={<Home />} />
                                <Route path="provenance" element={<Provenance />} />
                            </Route>
                        }
                        {!live &&
                            <Route>
                                <Route index element={<div className="img-fluid comingsoon">
                                    <img src="./comingsoon.png" alt="abokado banner" />
                                </div>} />
                            </Route>
                        }
                    </Routes>
                </ScrollToTop>
            </Router>
        </Provider>
    );
}
```


**Minter.js**

```
const Minter = (props) => {

    //State variables
    const [walletAddress, setWallet] = useState("");
    const [status, setStatus] = useState("");
    const [quantity, setQuantity] = useState("");
    const [totalSupply, setTotalSupply] = useState(1);
    const [buttonDisable, setButtonDisable] = useState(true);


    const { data: accountData, refetch, isLoading } = useAccount();
    console.log(accountData);

    const contract = useContractWrite(
        {
            addressOrName: contractAddress,
            contractInterface: contractABI.abi,
        },
        'mint',
    )

   console.log(contract);

    const onMintPressed = async () => {
        console.log("on Mint");
        console.log(quantity);

        contract.write(
            {
                args: [1],
                overrides: { value: ethers.utils.parseEther(0.02 + '') }
            });

    };


    return (
        <button id="mintButton" onClick={onMintPressed} >
            MINT NOW
        </button>
    );
};

export default Minter;
```

**Comment by tmm** [comment]
Looks like you need to memoize `createClient` or hoist oustide of `App`.

**Comment by bryantoh** [comment]
Its working now after move the <Provider client={client}> outside of <App>

**Comment by tae100k** [comment]
@tmm @bryantoh 
I hv exact same issue! And Id like to know why I hv to memoize or hoist to fix it! 

Is there any reason why wagmi not working preperly then?

I do know what hositing/memoization is but I cant understand what's the relationship between fixing this issue and hoisting/memoization
Thanks a lot!

**Comment by tmm** [comment]
@tae100k the wagmi Client is a singleton so must be only create once either initialized in the global scope or memoized in component body so it only runs once.

**Comment by tae100k** [comment]
@tmm Thank you so much! I almost pulled an all-nighter to find out why.

If you don't mind, can I ask you a few more questions by any chance?

1. Based on what you commented, will refreshing create another instance of the Client? How can refreshing affect a singleton instance? (I don't know so much details about singleton pattern. I know what it is and that's it)

2.It didn't happen in my local environment, but only on the dev server. Do you think is this relevant to the internal implementation of Client or React-Query?

3. I'm still not sure why hoist is related to this issue...? (I can understand that memo can solve this problem because client is created only once) Maybe we are referring to another hoisting..? not the one from javascript?

I'm very keen to know why this is happening to my code beyond solving this problem!
And please feel free to recommend any post that I can find out what I'm missing!

Thank you so much and have a wonderful Sunday!
