### ISSUE TITLE
[bug] useContractWrite fails if called with method that exists multiple times in the abi

### ISSUE THREAD

**Issue by cirsteve** [tmm/wagmi#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.3

### Current Behavior

If an abi includes a method name multiple times 
```
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_tokenName",
        "type": "string"
      }
    ],
    "name": "createToken",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_tokenName",
        "type": "string"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "createToken",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
```
and the method name that is duplicated in the abi is called with useWriteContract is throws the following error
```
TypeError: contractFunction is not a function at writeContract
```

### Expected Behavior

useWriteContract should be able to successfully execute a write transaction with a given method if the given args match the parameters

### Steps To Reproduce

Create an abi with duplicated method names. Call the duplicated method name with useContractWrite

**Comment by tmm** [comment]
Not able to reproduce because I need the address for this contract. Please add that and reopen.

https://codesandbox.io/s/loving-sun-3tmh6b?file=%2Fsrc%2FApp.tsx
