### ISSUE TITLE
Metamask is connected but signer is absent

### ISSUE THREAD

**Issue by hhff** [tmm/wagmi#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.0.3

### Current Behavior

I'm developing primarily against Metamask, and I've noticed that if I return to the project after a day or so (maybe I reset my computer), I find my project in a state where `account` is present, but `signer` is null.

For example, in this state, this code...
```js
const Wallet = () => {
  const { data: account } = useAccount();
  const { data: signer } = useSigner();

  console.log('account', account);
  console.log('signer', signer);
```

Will produce these logs:
<img width="219" alt="image" src="https://user-images.githubusercontent.com/2865404/167851515-180e9b89-880e-4f56-8a07-02c68f244ba7.png">

I have noticed that this case is when Metamask is re-prompting for password:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/2865404/167851690-5bf60b25-e9f3-4129-8319-8ea464969ea1.png">

### Expected Behavior

I'm under the impression that account and signer should both be present, or both absent; but never partially. (This may be a misunderstanding on my part).

### Steps To Reproduce

I'm pretty sure that restarting MacOS will require that Metamask wants you to reconfirm your password.

### Anything else?

It's most likely that this is expected behavior, given that it seems to be related to Metamask's internals. But my question for this library is -- how do you practically help a user recover from this state? What's wagmi's expected UX here for this case?

THANK YOU SO MUCH FOR THIS LIBRARY IT IS FANTASTIC

**Comment by hotkartoffel** [comment]
+1 we used to have a working flow with another library (useWallet) but hit into this issues with WAGMI

**Comment by tmm** [comment]
@hotkartoffel can you link to useWallet?

wagmi listens for when MM (or other injected providers) lock while a page that uses wagmi is open. Unfortunately, if MM is locked and the page is closed, wagmi isn't able to catch the event.

**Comment by hotkartoffel** [comment]
@tmm 
https://github.com/aragon/use-wallet 

Will also provide:
1. Two versions of our app w/ wagmi and w/ useWallet
2. Our public github repo

**Comment by tmm** [comment]
@hotkartoffel sounds great. please tag me when you post the links.

**Comment by hotkartoffel** [comment]
**Before wagmi**

App -> https://daonative-app-db9nowhcd-prologe.vercel.app/nfts/create

How to reproduce:
1. click on connect
2. connect with metamask
3. go to different webpage 
4. lock metamask
5. Go pack to url
6. fill in random info and click "Create collection"

Observed behavior: metmask pops up at step 5 and asks you to enter your password


**After wagmi**

App -> https://daonative-app-myp8jc48k-prologe.vercel.app/nfts/create

How to reproduce:
1. click on connect
2. connect with metamask
3. go to different webpage 
4. lock metamask
5. Go pack to url
6. fill in random info and click "Create collection"


Observed behavior: metamask shows you as connected (see top right), and clicking on "create collection" shows `N.getSinger not a function`

@tmm 

Extra infos:
- Github repo: https://github.com/daonative/app 
- Now we use rainbowkit on top of wagmi, but the examples show our wagmi implementation before we implemented rainbowkit

**Comment by hhff** [comment]
Thank you everyone. It's probably worth noting that I observed this behavior before `0.0.3`, also.

If the solution is simply "catch the intersection of `!!account && !signer` and trigger `disconnect()` that's AOK. Just want to be sure I'm handling this "the wagmi way".

**Comment by tmm** [comment]
Opened up https://github.com/tmm/wagmi/pull/447 for this. When the wagmi client attempts to autoconnect and no connection is made (e.g. MM is locked, wallet app disconnected when page is closed, etc.), the account is cleared since it is no longer connected.

**Comment by hhff** [comment]
Thank you @tmm - will check back when a new release is cut to validate it's working as expected.

**Comment by hhff** [comment]
Hi @tmm - checking in to see if you're next planning to but a release? (I know I could install from github but I'm not sure if main is considered stable)

**Comment by tmm** [comment]
very soon! been delayed with some other work this week.
