### ISSUE TITLE
[bug] The examples in the docs are showing the wrong version?

### ISSUE THREAD

**Issue by outdoteth** [tmm/wagmi#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

3.*

### Current Behavior

https://wagmi.sh/examples/connect-wallet

![Screenshot 2022-05-14 at 12 03 35](https://user-images.githubusercontent.com/37438950/168423019-92635dc8-8fec-4948-899e-bf33d681aed0.png)

why is it showing the old way to connect a wallet?

**Comment by tmm** [comment]
Looks correct to me. What's wrong with it?

**Comment by outdoteth** [comment]
Ah yea my bad. Was mixing it up with the rainbow kit docs wondering why the connect button wasn't there.
