### ISSUE TITLE
[bug] <title>

### ISSUE THREAD

**Issue by d2vin** [tmm/wagmi#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.0

### Current Behavior

ENS name stopped appearing in next JS app

### Expected Behavior

Expected ENS name to appear on ConnectButton after connected. 

### Anything else?

Just seems like the ENS service doesn't seem to be working. When I use 
`const { data: account } = useAccount();
  const { data: ensName } = useEnsName({ address: account?.address });`
 and log ensName i get null, feature was  working initially.

**Comment by tmm** [comment]
`null` means there is not an ENS name associated to the address.

Please create a minimal reproducible example and re-open this issue, but it seems like everything is working as intended.
