### ISSUE TITLE
[bug] If autoconnect is not true. Connector will not be assigned properly

### ISSUE THREAD

**Issue by daltoncoder** [tmm/wagmi#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.5

### Current Behavior

If you dont have autoconnect set to true you can not use wagmi. You will get a connector not found error

### Expected Behavior

To be able to access the connector with auto connect false

### Steps To Reproduce

turn off autoConnect

**Comment by tmm** [comment]
When does the "connector not found error" happen (e.g. using a specific hook, etc)?

Please provide a miminal reproducible example and re-open.
