### ISSUE TITLE
[bug] wait config not working correctly in useWaitForTransaction

### ISSUE THREAD

**Issue by YannikSood** [tmm/wagmi#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.1

### Current Behavior

Using the **wait config** like so:

<img width="663" alt="Screen Shot 2022-05-24 at 12 53 05 AM" src="https://user-images.githubusercontent.com/45681227/169951780-2151010e-b6d2-4b24-be7b-db292d1576fb.png">

I get the following error:

![Screen Shot 2022-05-24 at 12 53 52 AM](https://user-images.githubusercontent.com/45681227/169951875-97ab4687-e7af-4267-a0e7-9061b0e3e2b7.png)

I do not get any error using the hash config, but need to use the wait config.

### Expected Behavior

I am able to pass writeData?.wait to the wait config, which will return me a TransactionReceipt with the additional event data, as described in the ethers docs here: https://docs.ethers.io/v5/api/contract/contract/#Contract--write

However, at the moment just using the waitConfig does not work at all, and the hashConfig does not append the additional event data to the TransactionReciept, which I need. 

### Steps To Reproduce

Here is the write hook:

```
const { data: writeData, error: writeError, write } = useContractWrite(
      {
        addressOrName:  ContractAddress,
        contractInterface: ContractInterface,
      },
      'entry',
      { 
        args: [firstAnswer.trim().toLowerCase(), secondAnswer.trim().toLowerCase()],
          overrides: { 
            value: ethers.utils.parseEther("0.01") 
         }
      }
    )

```

and the wait hook:
```
const { data: waitData, isLoading: waitLoading } = useWaitForTransaction({
      // hash: writeData?.hash,
      wait: writeData?.wait,
      onSettled(data, error) {
        console.log("Settled", { data })
      }
    });
```

**Comment by jcflorville** [comment]
I have a same issue, do you fix?
