### ISSUE TITLE
[bug] Remix useSubmit() and useFetcher() makes wagmi connector get stuck on "reconnecting"

### ISSUE THREAD

**Issue by tmwBuidls** [tmm/wagmi#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.2

### Current Behavior

When using useSubmit() or useFetcher() in Remix, after submitting/ fetching the component re-renders however the wagmi connector gets stuck on "reconnecting" with `activeConnector` set to undefined despite `account.connector` being set. 

The above is with `autoConnect` set to true. However if I set that to false then the connector disconnects after submit/ fetch when the component re-renders.

### Expected Behavior

The connector should be connected.

### Steps To Reproduce

With the Remix example setup in this repo add a page with the below. After connecting, navigate to this page and click submit.

```
import type { ActionFunction } from "@remix-run/node";
import { Form, useSubmit } from "@remix-run/react";
import { json } from "@remix-run/node";
import { useConnect } from "wagmi";

export const action: ActionFunction = async () => {
  return json("Success", { status: 200 });
};

export default function Test() {
  const submit = useSubmit();
  const connector = useConnect();

  const handleSubmit = (event: any) => {
    event.preventDefault();
    submit(event.currentTarget, { replace: true });
  };

  return (
    <>
      {connector.status}

      <Form method="post" onSubmit={handleSubmit}>
        <button type="submit">
          Submit
        </button>
      </Form>
    </>
  );
}
```

**Comment by tmm** [comment]
Can you create a minimal reproducible example and re-open this issue?

**Comment by tmwBuidls** [comment]
FYI I fixed this, I had defined chains outside the scope of the functions and this for some reason caused something to happen post a submit/ fetch.
