### ISSUE TITLE
[bug] data is undefined when autoconnect is true

### ISSUE THREAD

**Issue by 0xc7nk1o** [tmm/wagmi#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.1

### Current Behavior

I set autoConnect to true when create client, see the following code:

```js
const { chains, provider } = configureChains(
  [chain.mainnet, chain.rinkeby],
  [publicProvider()]
);
const injectedConnector = new InjectedConnector({ chains: chains });
const wallectConnectConnector = new WalletConnectConnector({
  chains: chains,
  options: {
    qrcode: true,
  },
});
const client = createClient({
  autoConnect: true,
  connectors: [injectedConnector, wallectConnectConnector],
  provider,
});
```

And, I use `useConnect()` in my component.

```js
  const {
    data,
    connect,
    connectors,
    isConnected,
  } = useConnect();
```

Then, it shows that wallet is connected but the data is undefined.

```
activeConnector: InjectedConnector {_events: Events, _eventsCount: 3, id: 'injected', name: 'Brave Wallet', chains: Array(2), …}
connect: connector_ => {…}
connectAsync: connector_ => {…}
connectors: (2) [InjectedConnector, WalletConnectConnector]
data: undefined
error: null
isConnected: true
isConnecting: false
isDisconnected: false
isError: false
isIdle: false
isReconnecting: false
pendingConnector: undefined
reset: ƒ ()
status: "connected"
```

### Expected Behavior

`data` field should have the connected info.

### Steps To Reproduce

1. Setup the code that I mentioned "Current Behavior"
2. Connect MetaMask on the page
3. Refresh the page
4. Then `data` is undefined.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wonderful-leaf-npohso?file=/src/App.js

**Comment by tmm** [comment]
`useConnect` is a mutation hook so the `data` value is only defined when calling `connect` or `connectAsync`. If you need to access the connected account (address or connector) you should use [`useAccount`](https://wagmi.sh/docs/hooks/useAccount).
