### ISSUE TITLE
[bug] TypeError: Cannot read properties of null (reading 'call')

### ISSUE THREAD

**Issue by d2vin** [tmm/wagmi#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.3.5

### Current Behavior

I am trying to use the useSigner hook to get the signer and insert it into an ethers Contract instance. I am using Next JS and trying to build an NFT marketplace. When I leave click on a different page and come back to the initial page, everything seems to work normally. But when I refresh the initial page, I get the error. I put the signer variable from useSigner into the dependency array of my useEffect function which helped load the NFTs, but didn't get rid of the error.

### Expected Behavior

I expected  the ethers contract instance to use the signer variable from the useSigner hook.

### Steps To Reproduce

```
const Profile = () => {
  const [nfts, setNfts] = useState([]);
  const [loadingState, setLoadingState] = useState("not-loaded");
  const { data: signer } = useSigner();

  useEffect(() => {
    loadNFTs();
  }, [signer]);

  async function loadNFTs() {
    const contract = new ethers.Contract(
      marketplaceAddress,
      NFTMarketplace.abi,
      signer
    );
    const data = await contract.fetchItemsListed();
    // Map over items returned from smart contract and format them as well as fetch their token metadata
    const items = await Promise.all(
      data.map(async (i) => {
        const tokenUri = await contract.tokenURI(i.tokenId);
        const meta = await axios.get(tokenUri);
        let price = ethers.utils.formatUnits(i.price.toString(), "ether");
        let item = {
          price,
          tokenId: i.tokenId.toNumber(),
          seller: i.seller,
          owner: i.owner,
          image: meta.data.image,
          name: meta.data.name,
          description: meta.data.description,
        };
        return item;
      })
    );
    setNfts(items);
    setLoadingState("loaded");
  }
```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://5thj9v.sse.codesandbox.io/

### Anything else?

I find it interesting that even though I'm not connected to a network in sandbox, I still get the same unhandled runtime error:
TypeError: Cannot read properties of null (reading 'call')

**Comment by tmm** [comment]
The ethers `Contract` object requires `signerOrProvider` be defined (third argument). Your code does not check for this and passes `undefined` if `signer` does not exist (e.g. not loaded yet or wallet not connected).

A potential fix is to only call `loadNFTs` when `signer` is defined.

```ts
useEffect(() => {
  if (!signer) return
  loadNFTs()
}, [signer])
```

Next time, please use the [existing issue](https://github.com/tmm/wagmi/issues/500) and re-open it, instead of creating a new one.

**Comment by d2vin** [comment]
Thank you! Working now! Can I follow you on Twitter?
