### ISSUE TITLE
[bug] How can handle UserRejectedRequestError: User rejected request

### ISSUE THREAD

**Issue by smartdevcom** [tmm/wagmi#515]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

0.4.3

### Current Behavior

I am using Next.js with wagmi. when I try to switch network and click cancel button on metamask notification then error shows
Is there any way to get this signal when user rejects metamask actions? Or where should I handle this error? At least this error should not be shown.

![image](https://user-images.githubusercontent.com/45715420/170711681-8cb68788-1888-44a2-98f4-6f945a962631.png)

**Comment by tmm** [comment]
Please provide a minimal reproducible example and re-open.

**Comment by rvmelkonian** [comment]
we are also having this issue on some iOS devices, the user is shown just the QR code with no options to connect wallet on iOS 15 and other versions

**Comment by tmm** [comment]
@rvmelkonian seems related to this https://github.com/tmm/wagmi/issues/360#issuecomment-1111744660
