### ISSUE TITLE
[bug] Connecting to wrong network on some providers

### ISSUE THREAD

**Issue by enesozturk** [tmm/wagmi#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.4.2

### Current Behavior

I am using Wagmi with Rainbow Kit and did the following setup. Currently, I can log in with the MetaMask wallet as expected with the selected chains. But when I try to log in with the Rainbow or Coinbase wallets, I can still log in but when I check the provider details, I can see that the `chainId` is set to `1`. 

I needed to switch networks by using `useNetwork` hook manually but I don't want the users to do that. Just like the MetaMask, shouldn't it connect to the Polygon?

```js
const { chains, provider } = configureChains(
  [chain.polygon, chain.polygonMumbai],
  [alchemyProvider({ alchemyId: process.env.NEXT_PUBLIC_ALCHEMY_ID })]
);

const { connectors } = getDefaultWallets({
  appName: "Showtime",
  chains,
});

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});
```

### Expected Behavior

Other providers except MetaMask should also connect to the given chains on initialization. 

### Steps To Reproduce

- Login with MetaMask - You'll see it's connected to the Polygon
- Disconnect
- Login with Rainbow - It'll connect to the Ethereum chain. 

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-rainbow-example-8zx2x8

## Versions

```json
"@rainbow-me/rainbowkit": "0.2.0",
"wagmi": "^0.4.2",
"ethers": "^5.6.6",
```

**Comment by jxom** [comment]
@enesozturk – can you try provide a `chainId` attribute to the `WalletConnectConnector` config?

Example:

```tsx
const client = createClient({
  connectors: [
    new CoinbaseWalletConnector({
      chains,
      options: {
        chainId: chain.polygon.id,
        appName: 'wagmi',
      },
    }),
  ]
})
```

**Comment by enesozturk** [comment]
If I use a custom connector array just like you give example, on Rainbow Wallet modal I cannot see any wallet on the left. I need to use `connectorsForWallets` from **@rainbowme/rainbow-kit**.  But in this way, I cannot set chain id to the connectors:

```js
const connectors = connectorsForWallets([
  {
    groupName: "Recommended",
    wallets: [
      wallet.rainbow({ 
           chains,
           chainId: X, // here I cannot set chainId
      }),
      wallet.coinbase({ chains, appName: "Showtime" }),
      wallet.metaMask({ chains }),
    ],
  },
]);
```

In this way, I can see the wallet list on the modal but still connects the wrong chain. :/
