### ISSUE TITLE
[bug] Connects to the wrong local network on injected provider

### ISSUE THREAD

**Issue by Caruso33** [tmm/wagmi#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.4

### Current Behavior

The client is created with injected connector

```javascript
const wagmiClient = createClient({ autoConnect: true });

 <WagmiConfig client={wagmiClient}>
  <Component {...pageProps}
</WagmiConfig>
```

```javascript
const { connect } = useConnect({
    connector: new InjectedConnector(),
});
const network = useNetwork();
console.log("network", network);
```

Output:
```
{
activeChain: Object { id: 1337, name: "Localhost", network: "localhost", … }
​id: 1337
​​name: "Localhost"
​​network: "localhost"
​​rpcUrls: Object { default: "http://127.0.0.1:8545/" }
​​unsupported: true
...
```

but the Metamask extension is connected to `9545`

Also, when switching ganache and Metamask now to 8545:

```javascript
const { data: account } = useAccount();
console.log({ account });
const { data } = useBalance({
  addressOrName: account?.address,
});
console.log({value: data?.value?.toString()});
```

gives Output
```
{ value: "0" }
```

even the account with this address has 1000 on ganache UI and in Metamask.

Am I doing something incorrectly when working locally with ganache UI and wagmi?

### Expected Behavior

The network should be connected to 9545.

The ether amount should be correctly given, like it is in Metamask.

### Anything else?

![Screenshot 2022-05-30 at 19 35 20](https://user-images.githubusercontent.com/7684178/171039273-8acb4fc8-7f79-4259-b960-d3c35897dd36.png)
![Screenshot 2022-05-30 at 19 36 25](https://user-images.githubusercontent.com/7684178/171039347-b587e200-6ad6-4ab3-a158-eaefec506478.png)

**Comment by jxom** [comment]
Can you try pass through the chain to the connector?

```tsx
const { connect } = useConnect({
    connector: new InjectedConnector({ chains: [localhostChain] }),
});
```

Please re-open if that doesn't fix!

**Comment by Caruso33** [comment]
Thanks @jxom . I have tried the following unfortunately to no avail.

```javascript
import {
  chain, ...
  } from "wagmi

  const { connect } = useConnect({
    connector: new InjectedConnector({
      chains: [chain.localhost],
    }),
  });
```

The local chain doesn't appear under the network.chains property so I guess it's not set or where can I check it?

Thanks! 

![Screenshot 2022-05-31 at 13 55 38](https://user-images.githubusercontent.com/7684178/171167513-199e9fe0-5ac1-4fe1-8461-a879672061e3.png)

**Comment by tmm** [comment]
Looks like the provider is not chain-aware so it doesn't know to fetch from localhost.

```ts
const client = createClient({
  autoConnect: true,
  provider({ chainId }) {
    // Use JsonRpcProvider for localhost
    if (chainId === chain.localhost.id) return new providers.JsonRpcProvider()
    return new providers.AlchemyProvider(chainId)
  },
});
```

Also, wagmi does not support connecting directly to a specific chain right now as wallets do not have uniform support.

**Comment by Caruso33** [comment]
Hi @tmm ,

and thank you for your reply.

So this seems to connect to the right network. 

However now the incorrect account is selected (it connects to account 1 even an imported account is connected to the localhost website, and I am getting the error coming from `useBalance`
> can't access property "chainId", provider.network is undefined

![Screenshot 2022-06-01 at 10 13 55](https://user-images.githubusercontent.com/7684178/171360064-5a079ef1-3232-41f0-aebf-20bbc7f5628e.png)

![Screenshot 2022-06-01 at 10 14 03](https://user-images.githubusercontent.com/7684178/171360108-89261d13-9d90-490c-8fe2-2743bd948fcc.png)

![code](https://user-images.githubusercontent.com/7684178/171360132-e6133160-67da-42b9-9171-c5d6d35e84a4.png)

**Comment by Caruso33** [comment]
I disconnected account 1, so now the correct account is shown on useAccount (maybe related that it fails to update accounts when `autoConnect: true,`), however the error about provider.network still remains.

**Comment by Caruso33** [comment]
So it does work when correctly setting up the client:

```javascript
const { chains, provider } = configureChains(
  [...defaultChains, chain.hardhat],
  [
    alchemyProvider({ alchemyId: process.env.POLYGON_MUMBAI }),
    publicProvider(),
  ]
)

const client = createClient({
  autoConnect: true,
  connectors: [new InjectedConnector({ chains })],
  provider,
})
```
