### ISSUE TITLE
[bug] useSigner always returns null for signer after navigating with Next/Link

### ISSUE THREAD

**Issue by cnasc** [tmm/wagmi#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.3

### Current Behavior

When a user connects their wallet, the account and signer values from `useAccount` and `useSigner` respectively get populated as expected.

![image](https://user-images.githubusercontent.com/9300702/171637055-1283dad4-6968-4a99-9459-8b7caf577ed2.png)

However, once connected when I navigate to another page (using Next/Link) the account persists and the signer becomes null (and does not come back)

![image](https://user-images.githubusercontent.com/9300702/171637203-656de8dd-2d39-4c46-a892-9cb61f248f47.png)

### Expected Behavior

The signer should persist, or at least eventually repopulate instead of staying null.

### Steps To Reproduce

1. Visit https://interface-git-cjn-usesigner-debug-backed.vercel.app/network/rinkeby (debug build of our app with some `console.log` action)
2. Open developer tools to see logs in console
3. Connect wallet using button in top right of page
4. Observe that both `account` and `signer` are defined in the log that happens
5. Click "Create a Loan" on the top left of page
6. After page loads, observe that `account` is defined but `signer` is null in the log that happens. No further logs come through indicating that signer stays null

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/with-backed/backed-interface/pull/714

### Anything else?

We've gotten reports of this happening from users on various platforms and various wallets. I did see issue #444, but that appears to have been a different issue.

**Comment by tmm** [comment]
Seems like the issue could be related to the `client` being recreated multiple times. Can you make sure that [these dependencies are stable](https://github.com/with-backed/backed-interface/blob/d79aa00767fa64f3c33e177692dbd234d99e8947/components/ApplicationProviders/ApplicationProviders.tsx#L66=)? Ideally `createClient` is called in the global scope outside of any components.

If this doesn't fix it, mind creating a (more) minimal reproducible example and re-opening this issue?

**Comment by cnasc** [comment]
> Seems like the issue could be related to the `client` being recreated multiple times. Can you make sure that [these dependencies are stable](https://github.com/with-backed/backed-interface/blob/d79aa00767fa64f3c33e177692dbd234d99e8947/components/ApplicationProviders/ApplicationProviders.tsx#L66=)? Ideally `createClient` is called in the global scope outside of any components.

Memoizing `configureChains` and `getDefaultWallets` did resolve. We wanted to lean on recreating the client when changing network through the dropdown in our header, but have stepped around that by making network changes do a full page load. Thanks!
