### ISSUE TITLE
[bug] Error when trying to auto-connect coinbase wallet

### ISSUE THREAD

**Issue by kelokchan** [tmm/wagmi#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.4

### Current Behavior

When I have `autoConnect` set to `true` and connected to coinbase wallet, I will be getting error when refreshing the page. 
```
Uncaught (in promise) TypeError: Cannot destructure property 'chainId' of 't' as it is undefined.
    at N.connect (wagmi-core-connectors-coinbaseWallet.esm.js:67:7)
    at P.autoConnect (client-61f14c97.esm.js:554:36)
    at async wagmi.esm.js:201:26
```

### Expected Behavior

Expected to be able to reconnect to the coinbase wallet after refresh

### Steps To Reproduce

1. Set `autoConnect to `true` in `createClient`
2. Connect to `coinbase`
3. Refresh the page

**Comment by tmm** [comment]
Fixed in `wagmi@0.4.8` (and `@wagmi/core@0.3.7`).
