### ISSUE TITLE
[bug] Disconnects after switching network

### ISSUE THREAD

**Issue by enesozturk** [tmm/wagmi#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.4.6

### Current Behavior

I'm using Wagmi with Rainbow Kit for our project. Today I realized that when I change the network I connected, `data` from the `useAccount` hook and `activeChain` from the `useNetwork` start returning null and undefined. The weird thing is that it's not happening every time, looks like there is a race condition and when I keep switching networks, it disconnects me at a point.

You can try with the link I created on CodeSandbox.

### Expected Behavior

Keep returning data with the switched network. As a result, it disconnects me, I mean I see the rainbow button in the disconnected state.

### Steps To Reproduce

- Sign in with MetaMask on Mainnet
- **On MetaMask extension**, switch another network from dropdown
- Keep doing this. Especially when you switch from Mainnet to Polygon or vice versa cause it faster.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/magical-gwen-8zx2x8?file=/src/App.js:253-263

### Anything else?

https://user-images.githubusercontent.com/19428358/172438473-f0cc500a-4d3c-4a6e-8a21-f0dd0f1cce38.mov

**Comment by tmm** [comment]
Unfortunately, there is a bug with MetaMask that causes this when using the extension interface https://github.com/MetaMask/metamask-extension/issues/13375#issuecomment-1087023057

We try to mitigate this as much as possible when switching networks programmatically with wagmi (e.g. `useNetwork` and `shimChainChangedDisconnect` defaulted to `true` for `MetaMaskConnector`).

**Comment by enesozturk** [comment]
Thanks for the response @tmm 🤞🏽

**Comment by ryanberckmans** [comment]
As indicated in this thread and in https://github.com/MetaMask/metamask-extension/issues/13375, despite passing `{ shimDisconnect: true, shimChainChangedDisconnect: true }`, the wallet can still involuntarily disconnect when the user switches the chain from inside the metamask browser extension.

Yet, when testing this on a mature non-wagmi app such as [Uniswap](https://app.uniswap.org/#/swap), we're able to switch (to, from) any chain in the metamask browser extension without the Uniswap UI involuntarily disconnecting. What is it that the Uniswap UI is doing that wagmi isn't doing now, and could we start doing it?

Alternatively, maybe my wagmi is misconfigured and there is something else I should be doing to prevent the metamask browser extension from involuntarily disconnecting when switching chains inside the extension?

For reference:

```typescript
new MetaMaskConnector({
  chains,
  options: {
    shimDisconnect: true,
    shimChainChangedDisconnect: true,
  },
}),
```

**Comment by tmm** [comment]
Looks correct! Want to create a new issue with a minimal reproducible example and I can take a look?

**Comment by ryanberckmans** [comment]
> Looks correct! Want to create a new issue with a minimal reproducible example and I can take a look?

https://github.com/wagmi-dev/wagmi/issues/1941
