### ISSUE TITLE
[bug] Error when passing connector to connect

### ISSUE THREAD

**Issue by taycaldwell** [tmm/wagmi#588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.12

### Current Behavior

I currently get an error when passing a connector to `connect()` using the following syntax:

```
const { connect, connectors } = useConnect();

<Button onClick={() => {
    connect(connectors[0]);
}}>
```

Error:
```
index.js:27 Error: connector is required
    at Object.mutationFn$5 [as mutationFn] (wagmi.cjs.dev.js:746:25)
    at Object.fn (mutation.js:91:31)
    at run (retryer.js:112:31)
    at createRetryer (retryer.js:158:5)
    at executeMutation (mutation.js:85:49)
    at Mutation.execute (mutation.js:140:26)
```

However, the following syntax works:

```
const { connect, connectors } = useConnect();

<Button onClick={() => {
    connect({ connector: connectors[0] });
}}>
```

### Expected Behavior

Based on the method signature for `connect()`, I would expect to be able to pass a connector directly without having to treat it as a `Partial<ConnectArgs>`:

`readonly connect: (connectorOrArgs?: Connector<any, any> | Partial<ConnectArgs> | undefined) => void;`

### Steps To Reproduce

1. Instantiate your connectors
2. Create a wagmi client and pass it your connectors
3. Use the `useConnect` React hook to import `connect` and `connectors`
4. Pass a `connector` from `connectors` as an argument to `connect` upon a button click
5. Observe error

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/coinbase-wallet-demo-integrate-with-wagmi-forked-yq0cj7?file=/src/Modal.js

**Comment by jxom** [comment]
I can't seem to open the CodeSandbox. Getting a "Sandbox not found".

**Comment by taycaldwell** [comment]
I've updated the codesandbox link. Please try again.

**Comment by jxom** [comment]
In `0.5.0`, we will be removing the ability to directly pass in a `connector` to `connect` & `connectAsync`. Instead, it will need to be defined in an object:

```diff
import { useConnect } from 'wagmi'
function App() {
  const { connect, connectors } = useConnect()
  return (
    <button
-     onClick={() => connect(connectors[0])}
+     onClick={() => connect({ connector: connectors[0] })}
    >
      Connect
    </button>
  )
}
```
