### ISSUE TITLE
[bug] missing assets/wallet-logo

### ISSUE THREAD

**Issue by dcsan** [tmm/wagmi#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

4.1.2

### Current Behavior

have installed the module, however on another dev checking out we're getting the error below.
note this seems only for node v18
and when installing use `yarn` and not `npm`

```
./node_modules/wagmi/node_modules/@coinbase/wallet-sdk/dist/CoinbaseWalletSDK.js
Module not found: Can't resolve './assets/wallet-logo' in '/Users/dc/dev/alfalabs/plug-bot/client/node_modules/wagmi/node_modules/@coinbase/wallet-sdk/dist'
```

this is indeed an import in the coinbase dependency of wagmi:

![image](https://user-images.githubusercontent.com/514002/174666919-0ca8f46f-c8d3-4b98-aeee-be2d565e1e24.png)

but that file (or any `assets` dir) doesn't exist in the dist.

when i look in there it appears to be empty

```
 ls -la node_modules/wagmi/node_modules/@coinbase
total 0
drwxr-xr-x  2 dc  staff   64 Jun 20 12:28 .
drwxr-xr-x  7 dc  staff  224 Jun 20 12:28 ..
```

### Expected Behavior

should be able to startup our server when using wagmi package without dependency of dependency problems.

### Steps To Reproduce

hard to say, but 

- create a project 
- run with node v18
- on a separate machine use `yarn` to install packages

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

not now

### Anything else?

not now.

**Comment by jxom** [comment]
I am unable to reproduce this. Please provide a minimal reproducible example and re-open the issue. 😊
