### ISSUE TITLE
[bug] Initial status of useWaitForTransaction is error

### ISSUE THREAD

**Issue by iralution** [tmm/wagmi#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.12

### Current Behavior

When I use the `useWaitForTransaction` hook without a hash provided, the initial value of `status` is `error`. 
But there is no real error and if I pass a `onError` callback, it is not called.
When the hash is provided, it switches correctly to `loading`.

### Expected Behavior

The initial status should be `idle` as it's expected that the data object from e.g. `useContractWrite` is `undefined` until the write is executed.

### Steps To Reproduce

```
const {
    write,
    data: writeData,
  } = useContractWrite({ addressOrName: '...address here ...', contractInterface }, 'callMeBaby', { args });

const {
    isLoading,
    isError,
    data,
    status,
  } = useWaitForTransaction({
    hash: writeData?.hash, // is undefined until write has been successfully called and writeData contains a hash
    onError(error) {
      // this is not called
      console.log('Error', error);
    }
  });

console.log(status) // <- logs 'error' initially
console.log(isError) // <- is initially true
```

**Comment by jxom** [comment]
I can't seem to reproduce this one. What is the error message (`error` from `useWaitForTransaction`)? Can you please upload a reproducible example to [CodeSandbox](https://codesandbox.io/) and then re-open this issue?

Thanks!
