### ISSUE TITLE
ShimDisconnect for Metamask connector does not seem to work

### ISSUE THREAD

**Issue by ElasticBottle** [tmm/wagmi#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.12

### Current Behavior

when calling `disconnect` from the `useDisconnect` hook, the `data` field from `useAccount` becomes `undefined | null` even when `shimDisconnect: false` in the `MetaMaskConnector`

### Expected Behavior

when calling `disconnect` from the `useDisconnect` hook, the `data` field from `useAccount` should not be `undefined | null` when `shimDisconnect: false` in the `MetaMaskConnector`

### Steps To Reproduce

Follow the [connect wallet guide](https://wagmi.sh/examples/connect-wallet) with `shimDisconnect: false` on metamask

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/embed/recursing-cookies-dr7kmo?fontsize=14&hidenavigation=1&theme=dark

**Comment by jxom** [comment]
I seem to be getting an error on your sandbox.

<img width="615" alt="Screen Shot 2022-06-24 at 3 35 34 pm" src="https://user-images.githubusercontent.com/7336481/175469315-32b7f8e1-cb2c-4a40-8ab6-d8e529a7a54b.png">

**Comment by ElasticBottle** [comment]
hmm you can try this: https://codesandbox.io/s/silent-frog-r9jhh3?file=/src/Profile.js:78-79

**Comment by tmm** [comment]
`shimDisconnect` is meant to simulate [`window.ethereum.disable()`/`window.ethereum.close()`](https://github.com/MetaMask/metamask-extension/issues/10353) by preventing automatic (re)connection to the app. It does not change the behavior of `useDisconnect`.
