### ISSUE TITLE
[bug] useEnsName Returns null When Attempting To Fetch ENS From Gnosis Safe

### ISSUE THREAD

**Issue by joeblau** [tmm/wagmi#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.12

### Current Behavior

Calling useEnsName on an Ethereum address that is a gnosis safe returns `null`

Sample Code.

```typescript
  const { data: ensName } = useEnsName({
    address: "0xd2aa6323f32dae7aa8e20734260204a6ee7c1e94",
  });
```

In this example `ensName` will be `null`.

### Expected Behavior

Calling useEnsName on an Ethereum address that is a gnosis safe returns `atomize.eth`

```typescript
  const { data: ensName } = useEnsName({
    address: "0xd2aa6323f32dae7aa8e20734260204a6ee7c1e94",
  });
```

In this example `ensName` should be `atomize.eth`

### Steps To Reproduce

```bash
git clone https://github.com/joeblau/wagmi-gnosis
cd wagmi-gnosis
yarn install
yarn dev
open https://localhost:3000
```

In `pages/index.tsx` toggle between the two sets of code to view the results.

```typescript
  // doodles.eth/poopie.eth wallet works
  const { data: ensName } = useEnsName({
    address: "0xC35f3F92A9F27A157B309a9656CfEA30E5C9cCe3",
  });

  // atomize.eth gnosis safe does not work
  const { data: ensName } = useEnsName({
    address: "0xd2aa6323f32dae7aa8e20734260204a6ee7c1e94",
  });

  return (
    <div>
      <h1>{`ensName: ${ensName}`} </h1>
    </div>
  );
```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/joeblau/wagmi-gnosis

### Anything else?

The result for `0xd2aa6323f32dae7aa8e20734260204a6ee7c1e94` or `atomize.eth`
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1218847/175832647-d09c63b5-1134-4d6a-aec9-0c4f760057b3.png">

The result for `0xC35f3F92A9F27A157B309a9656CfEA30E5C9cCe3` or `poopie.eth`
<img width="352" alt="image" src="https://user-images.githubusercontent.com/1218847/175832664-782062da-24b2-4a89-bbc5-d0a1bedd85e6.png">

**Comment by tmm** [comment]
`0xd2aa6323f32dae7aa8e20734260204a6ee7c1e94` is the registrant/controller of [`atomize.eth`](https://app.ens.domains/name/atomize.eth/details), but it's reverse record is set to `0xb6542DE25941D3ca4Eb839F6C9096823e09Ab5B4`.

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/6759464/175832875-b894e976-cf07-4c22-81db-b43d2d1f6c6a.png">
