### ISSUE TITLE
[bug] WebSocket interface for connecting to network - typescript

### ISSUE THREAD

**Issue by danilo-89** [tmm/wagmi#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.0

### Current Behavior

> (property) webSocketProvider?: WebSocketProvider | ((config: {
>     chainId?: number | undefined;
> }) => WebSocketProvider | undefined) | undefined
> WebSocket interface for connecting to network
> 
> Type '({ chainId }: { chainId?: number | undefined; }) => { chains: Chain[]; } | undefined' is not assignable to type 'WebSocketProvider | ((config: { chainId?: number | undefined; }) => WebSocketProvider | undefined) | undefined'.
>   Type '({ chainId }: { chainId?: number | undefined; }) => { chains: Chain[]; } | undefined' is not assignable to type '(config: { chainId?: number | undefined; }) => WebSocketProvider | undefined'.
>     Type '{ chains: Chain[]; } | undefined' is not assignable to type 'WebSocketProvider | undefined'.
>       Type '{ chains: Chain[]; }' is not assignable to type 'WebSocketProvider'.
>         Type '{ chains: Chain[]; }' is missing the following properties from type 'WebSocketProvider': _websocket, _requests, _detectNetwork, _subIds, and 92 more.ts(2322)
> client.d.ts(23, 5): The expected type comes from property 'webSocketProvider' which is declared here on type 'CreateClientConfig<(AlchemyProvider & { chains: Chain[]; }) | (FallbackProvider & { chains: Chain[]; }), WebSocketProvider>'

This issue appeared in 0.5.0.  
(nextjs example)
```
import * as React from 'react'
import type { AppProps } from 'next/app'
import NextHead from 'next/head'

import {
  WagmiConfig,
  configureChains,
  createClient,
  defaultChains,
} from 'wagmi'
import { alchemyProvider } from 'wagmi/providers/alchemy'
import { CoinbaseWalletConnector } from 'wagmi/connectors/coinbaseWallet'
import { InjectedConnector } from 'wagmi/connectors/injected'
import { MetaMaskConnector } from 'wagmi/connectors/metaMask'
import { WalletConnectConnector } from 'wagmi/connectors/walletConnect'

const alchemyId = process.env.NEXT_PUBLIC_ALCHEMY_ID

const { chains, provider, webSocketProvider } = configureChains(defaultChains, [
  alchemyProvider({ alchemyId }),
])

const client = createClient({
  autoConnect: true,
  connectors: [
    new MetaMaskConnector({ chains }),
    new CoinbaseWalletConnector({
      chains,
      options: {
        appName: 'wagmi',
      },
    }),
    new WalletConnectConnector({
      chains,
      options: {
        qrcode: true,
      },
    }),
    new InjectedConnector({
      chains,
      options: {
        name: 'Injected',
        shimDisconnect: true,
      },
    }),
  ],
  provider,
  webSocketProvider,
})
```

### Expected Behavior

There should be no typescript error.

### Steps To Reproduce

Open example from [https://github.com/tmm/wagmi/tree/main/examples/next](https://github.com/tmm/wagmi/tree/main/examples/next) in vscode. Error appearing in file: src/pages/_app.tsx

**Comment by BraedenNorris** [comment]
Hey! I'm having this same issue. It looks like it's due to an update to the configureChains.ts file that occurred during the 0.5.0 upgrade.

I think I isolated the problematic code and developed a fix locally. I'm going to test a little more and then submit a PR which I'll reference here once it's up.
