### ISSUE TITLE
[bug] Unable to Connect to Coinbase Wallet on iOS

### ISSUE THREAD

**Issue by JaegarSarauer** [tmm/wagmi#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.4.12

### Current Behavior

Attempting to connect to the Coinbase Wallet using the Coinbase Wallet Connector will fail silently on iOS using the wallet's built-in browser.

### Expected Behavior

The connection status should update with a green check mark.

### Steps To Reproduce

 - Download Coinbase Wallet App from the [App Store](https://apps.apple.com/ca/app/coinbase-wallet-nfts-crypto/id1278383455).
 - Setup wallet
 - Visit the [Coinbase Wallet Demo](https://codesandbox.io/s/coinbase-wallet-demo-integrate-with-wagmi-psv1j0) in the Coinbase Wallet Browser.
 - Click the "Connect Wallet" button.
 - Click "Coinbase Wallet" from the modal.
 - Coinbase Wallet will not respond to the connect request.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/coinbase-wallet-demo-integrate-with-wagmi-psv1j0

### Anything else?

A console error appears in the code sandbox: 
```
makeWeb3Provider@
@

asyncFunctionResume@[native code]

@[native code]

promiseReactionJobWithoutPromise@[native code]

promiseReactionJob@[native code]
```

I have tested the coinbase wallet connection using Coinbase's other examples. I am able to create a connection using web3-react. Follow the above repro steps with the [web3-react sandbox](https://codesandbox.io/s/web3react-demo-mqlydu) to witness expected behaviour.

Below is a screenshot of the modal just before attempting to connect:
![image](https://user-images.githubusercontent.com/9870394/176036722-aed8c37c-d1ae-4aa1-9ddc-796e98179bab.png)

**Comment by melissafzhang** [comment]
@tmm I'm still seeing the same issue on 0.5.2

**Comment by melissafzhang** [comment]
@tmm created a repro [here](https://codesandbox.io/s/romantic-wind-bgxzwn)

**Comment by JaegarSarauer** [comment]
This issue was fixed for me on version `0.5.0`.

**Comment by melissafzhang** [comment]
@JaegarSarauer interesting I'm still having the same issue even with 0.5.0. I've updated the [codepen](https://codesandbox.io/s/romantic-wind-bgxzwn) as well

**Comment by melissafzhang** [comment]
Just closing the loop here. Looks like the issue was fixed! My issue was that `useConnect` was throwing an error since Coinbase wallet was already connected. Feels like it probably should just return the account data instead of throwing an error.
