### ISSUE TITLE
[bug] useContractInfiniteRead not reevaluating when contracts length changes

### ISSUE THREAD

**Issue by chillichelli** [tmm/wagmi#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.0

### Current Behavior

Whenever the contracts array changes, useContractInfiniteReads is not re-evaluating

### Expected Behavior

I would expect the hook to recognize the data being stale and revalidate.

### Steps To Reproduce

![Schermafbeelding 2022-06-29 om 15 34 48](https://user-images.githubusercontent.com/80068137/176449575-ed2b8c5e-f6af-46ed-9879-315e64df3aeb.png)

When account is undefined initially it returns an empty array

```
  const contracts = useMemo(
    () =>
      account
        ? validatedTokenAddresses.map((token) => ({
            chainId,
            addressOrName: token,
            contractInterface: erc20ABI,
            functionName: 'balanceOf',
            args: [account],
          }))
        : [],
    [validatedTokenAddresses, chainId, account]
  )

  // Wallet Balances
  const {
    data,
    isError: isTokensError,
    isLoading: isTokensLoading,
  } = useContractInfiniteReads({
    cacheKey: 'tokenBalances',
    contracts: () => contracts,
    staleTime: 2_000,
  })
```

**Comment by jxom** [comment]
I'd recommend using `useContractReads` if this doesn't rely on a pagination/next index pattern.
