### ISSUE TITLE
[bug] useContractReads always returning a [null]

### ISSUE THREAD

**Issue by magiclars-off** [tmm/wagmi#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.5

### Current Behavior

Trying to read one or multiple contracts using `useContractReads` always returns `[null]`

input:  
```
import { erc721ABI, useContractReads } from 'wagmi';

[{
        addressOrName: '0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d',
        contractInterface: erc721ABI,
        functionName: 'tokenURI',
        args: 1,
        chainId: 1,
}]
```
      
Same object does succeed with useContractRead

![image](https://user-images.githubusercontent.com/62888804/176692325-b1f595f9-b17b-4e61-8649-6e8eb0ef1205.png)

**Comment by jxom** [comment]
I created a minimal CodeSandbox and could not reproduce this issue. Maybe check if the ABI at the contract address matches the ABI that you specified?

Here is my CodeSandbox demonstrating the same thing but with the [Loot contract](https://etherscan.io/address/0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7#code):

https://codesandbox.io/s/dreamy-river-0uer8i?file=/src/App.js

**Comment by matthewlilley** [comment]
@jxom I was having the same issue migrating a very basic hook to wagmi multicall from redux multicall. At first I thought probably just human error, but after some time I can't see anything obviously wrong here. Old returns expected data, new returns [null] or undefined consistently.

![Screenshot_272](https://user-images.githubusercontent.com/6063350/176890890-62c36a26-090e-4fbb-bb57-8e2d86da2663.png)

**Comment by matthewlilley** [comment]
I'll fork your code sandbox and hard code the data so you can see there is defintiely an issue here.

**Comment by JohnSmithyy** [comment]
I'm actually facing this exact same issue. useContractReads will randomly stop working and start returning null values. 

Looking in my browser console, I do see that it says multicall is not supported on my local network which is fine because I assume that if it can't do a multicall, it will just do each contract read in the reads function one after the other instead of a batch.

But not sure why it stops working all together randomly. My minimal example is pretty similar to what OP posted except I don't pass in a chainid.

**Comment by JohnSmithyy** [comment]
I am curious how #645  got resolved.

**Comment by jxom** [comment]
@JohnSmithyy – got a codesandbox you can push up that reproduces this issue?

**Comment by JohnSmithyy** [comment]
> @JohnSmithyy – got a codesandbox you can push up that reproduces this issue?

Unfortunately not since I cannot replicate the issue consistently on a codesandbox. It happens randomly on my local network, not sure why. I'm thinking it has something to do with multicall since moving to useContractRead for each function works without issues but useContractReads will return null values randomly time to time.

**Comment by JohnSmithyy** [comment]
For example here is my localchain setup (using rainbowkit):

```
const localChain: Chain = {
  id: 31337,
  name: "Local",
  network: "local",
  nativeCurrency: {
    decimals: 18,
    name: "Local",
    symbol: "ETH",
  },
  rpcUrls: {
    default: "http://127.0.0.1:8545/",
  },
  testnet: false,
  multicall: {
    address: "0x5ba1e12693dc8f9c48aad8770482f4739beed696",
    blockCreated: 12336033,
  },
};
```

This does not work at all. I have to remove the multicall param for things to work.

**Comment by ricardopinto** [comment]
Experiencing the same issue with `useContractInfiniteReads()` on a local chain, without multicall support on this chain. Wagmi randomly returns `null` entries in the `data.pages[0]` array

**Comment by jxom** [comment]
Can you provide a minimal reproducible example?

**Comment by ricardopinto** [comment]
It's not reproducible 100% of the time but I can explain the setup:

1. Created an ERC721 contract exposing a function like `getNFTDataByID(uint256 id) public view returns(NFTData memory)`, and minted ~900 of these.
2. On the frontend used wagmi like this to list all of them:
  ```
    const contractConfig = {
        addressOrName: "0xaddress_goes_here",
        contractInterface: "<abi_goes_here>",
    }
    const perPage: number = 1000
    const { data } = useContractInfiniteReads({
        cacheKey: 'nftDataCache',
        ...contractConfig,
        ...paginatedIndexesConfig(
            (index) => {
                console.log('index', index)
                return {
                ...contractConfig,
                functionName: 'getNFTDataByID',
                args: [index],
            }},
            { start: 900, perPage: perPage, direction: 'decrement' },
        ),
        suspense: true,
    })
  ```

3. Randomly `data.pages[0]` array has some `null` entries

Hope it helps

**Comment by Deg3n3rate** [comment]
@JohnSmithyy Happened to run into a similar issue and just wanted to point out that wagmi is using `Multicall3` under the hood as can be shown here: https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/contracts/multicall.ts#L89

and you're specifying a `Multicall2` address in your chain config. Multicall3 Implementation on eth mainnet can be found here: https://etherscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11#code

Hope this helps

**Comment by ricardopinto** [comment]
Great call out @Deg3n3rate . I didn't have any multicall deployed on my private network and it still worked, although slow, with that issue happening randomly. Yesterday after digging deeper into that same code I noticed the dependency on Multicall3, so I searched around and found an implementation that works wonders here: https://github.com/NFEL/multicall-python-clinet/blob/master/src/Multicall3.sol . Since the deployment of `Multicall3`, the `null` issue has not manifested again yet.

Hope it helps anyone coming across this

**Comment by JohnSmithyy** [comment]
> @JohnSmithyy Happened to run into a similar issue and just wanted to point out that wagmi is using `Multicall3` under the hood as can be shown here: https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/contracts/multicall.ts#L89
> 
> and you're specifying a `Multicall2` address in your chain config. Multicall3 Implementation on eth mainnet can be found here: https://etherscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11#code
> 
> Hope this helps

Thanks for your reply.

I've noticed this too but I'm forking mainnet off a specific block so I had to resort to using `Multicall2 `instead since `Multicall3 `does not exist yet.

**Comment by ricardopinto** [comment]
@JohnSmithyy that was precisely what I did. If I ever run in the same `null` issue I'll write down here.

**Comment by JohnSmithyy** [comment]
> @JohnSmithyy that was precisely what I did. If I ever run into the same `null` issue I'll write down here.

Could you share your local network configuration? 

I have multicall3 setup but now just returns stale data instead of nulls. So when I do a deposit on my contract, it still shows the previous / old balance instead.

**Comment by ricardopinto** [comment]
@JohnSmithyy it goes something like this:

```typescript
const myTestnetChain: Chain = {
  id: 7200,
  name: 'My Testnet',
  network: 'my-testnet',
  iconUrl: null,
  iconBackground: '#fff',
  nativeCurrency: {
    decimals: 18,
    name: 'ETH',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: 'https://my.testnet.local',
  },
  blockExplorers: {
    default: {
      name: "WinrScan",
      url: 'https://myscan.testnet.local/'
    },
  },
  multicall: {
    address: "0xaddress_goes_here",
    blockCreated: 123456,
  },
  testnet: true,
};
```

**Comment by JohnSmithyy** [comment]
Yeah that matches my setup too @ricardopinto

Weird that it doesn't work. Are you also forking mainnet?

**Comment by ricardopinto** [comment]
@JohnSmithyy  No forking, just a simple private network using geth.

**Comment by JohnSmithyy** [comment]
> @JohnSmithyy No forking, just a simple private network using geth.

Interesting. I'm using a hardhat node/workflow.
