### ISSUE TITLE
[bug] useContractReads returns unstable data

### ISSUE THREAD

**Issue by chillichelli** [tmm/wagmi#644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.5

### Current Behavior

When setting `watch` to false in `useContractReads` the data that is returned is unstable.

### Expected Behavior

I would expect the data to be stable

### Steps To Reproduce

```
  const {
    data,
    isError: isTokensError,
    isLoading: isTokensLoading,
  } = useContractReads({
    contracts,
    // cacheTime: 20_000,
    keepPreviousData: true,
    watch: false,
  })

  useEffect(() => {
    console.log('unstable')
  }, [data])
  ```

**Comment by jxom** [comment]
Hi. What do you mean by "unstable"? Can you upload a minimal reproducible example and then re-open the issue? Thanks!

**Comment by matthewlilley** [comment]
Hey @jxom, we were migrating from redux multicall to wagmi multicall and run into a number of performance issues, after some digging it appeared that data from useContractReads is not preserving equality in most cases, despite the data not actually changing, and even with watch false.

**Comment by chillichelli** [comment]
Unstable meaning that on every render the reference to the data changes. If the parameters being passed to `useContractReads` have the same references, the returned reference of data shouldn't change as well.

**Comment by jxom** [comment]
Oh right. Interesting. `useContractReads` uses react-query under-the-hood which has structural sharing built in (see image below), so I'm not sure why this is happening. I'll take a closer look into this on Monday!

![image](https://user-images.githubusercontent.com/7336481/176886776-e2ce3de0-18ae-4e73-a14a-b503b29b4496.jpeg)

**Comment by matthewlilley** [comment]
> Oh right. Interesting. `useContractReads` uses react-query under-the-hood which has structural sharing built in (see image below), so I'm not sure why this is happening. I'll take a closer look into this on Monday!
> 
> ![image](https://user-images.githubusercontent.com/7336481/176886776-e2ce3de0-18ae-4e73-a14a-b503b29b4496.jpeg)

Yes, although not familiar with react-query I expected this is exactly what *should* be happening under the hook. Actually, in many cases it is. I tested useBalance hook as an example because balances don't change often, but refetching will happen regularly, and equality is preserved. However, if I wrote a useContractReads hook which fetching N balances, you'd expect the same behavior, however eqaulity is always lost, which causes a huge amount of performance issues.
