### ISSUE TITLE
[bug] useContractReads data instability

### ISSUE THREAD

**Issue by matthewlilley** [tmm/wagmi#648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

useContractReads returns unstable data, equality is always lost despite underlying data being exactly the same

### Expected Behavior

In cases where the underlying data has not changed, for equality to be preserved. 

### Steps To Reproduce

repro below

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/small-smoke-2i7b0q?file=/src/App.js

**Comment by tmm** [comment]
Off chance this might be related https://github.com/TanStack/query/issues/3772

**Comment by matthewlilley** [comment]
Might be useful to look at for this one: https://github.com/Uniswap/redux-multicall/blob/main/src/hooks.ts#L55

**Comment by jxom** [comment]
Opened a fix here: #659.

React Query's data comparison function does not support the ethers `Result` type as it is not JSON serializable. I have added an `isDataEqual` flag that defaults to our implementation of `deepEqual` (RQ also does a deep equal implementation for their structural sharing), but you can also provide your own ((like you did here)[https://github.com/Uniswap/redux-multicall/blob/dfa4cf7adca0bf7408426eb8e39476da59deebd3/src/hooks.ts#L80])!

**Comment by matthewlilley** [comment]
> Result

That makes sense, feels like this would be a valuable PR to ethers too now I think about it. I wonder if the same is true for ethers v6. Yeah, it seems this would work, but would like to test if you'd put up a pre-release version. I'd be happy to do that if you can.

**Comment by jxom** [comment]
@matthewlilley – can you check `0.5.7`?
