### ISSUE TITLE
[bug] WalletConnect with Remix-run 1.6.3 Error

### ISSUE THREAD

**Issue by Nikitulb** [tmm/wagmi#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

wagmi 0.5.5, remix 1.6.3

### Current Behavior

Error: Cannot read properties of undefined (reading 'constructor')

### Expected Behavior

Wallect connect works correctly

### Steps To Reproduce

Start your examples/remix and click on wallet connect button 

### Anything else?

Works with remix 1.4.3. But doesn't work with 1.6.3

**Comment by tmm** [comment]
Please create a minimal reproducible example and re-open.
