### ISSUE TITLE
[bug] useDisconnect not disconnecting from Metamask

### ISSUE THREAD

**Issue by dhavalsoni2001** [tmm/wagmi#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.12

### Current Behavior

Whenever I connect one Metamask account and then disconnect it still shows connected on metamask.
<img width="354" alt="Screenshot 2022-07-08 at 9 39 32 PM" src="https://user-images.githubusercontent.com/11704436/178030034-72dfeb62-c1e2-480d-a6a5-ec330573e1e3.png">

### Expected Behavior

It should be disconnected from the Metamask.

### Steps To Reproduce

- Login with Metamask,
- useDisconnect method to log out,
- Check Metamask it still shows connected, it should show Not. Connected

**Comment by tmm** [comment]
MetaMask [doesn't support programmatic disconnect](https://github.com/MetaMask/metamask-extension/issues/10353#issuecomment-1011129684). wagmi simulates this with the [`shimDisconnect`](https://wagmi.sh/docs/connectors/metaMask#shimdisconnect=) and [`UNSTABLE_shimOnConnectSelectAccount`](https://wagmi.sh/docs/connectors/metaMask#unstable_shimonconnectselectaccount=) flags.
