### ISSUE TITLE
[Disconnect Wallet] Disconnect wallet seems like a dummy feature and doesn't work the way it's supposed to work.

### ISSUE THREAD

**Issue by Deveshb15** [tmm/wagmi#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.0.17

### Current Behavior

The disconnect wallet feature from the useAccount hook doesn't seem to disconnect the wallet completely and just shows that it is disconnected on the client side as I have autoconnect enabled while declaring the Provider in the App.js even after disconnecting the wallet if I reload the app it gets connected to the account that I connected previously.

### Expected Behavior

The disconnect feature should remove the app from the metamask connected sites of the user is what I believe and I'm not sure if its possible but what I've seen other packages do is they change the account state to undefined and even after a reload it stays undefined unless and until the user connects wallet again.  

### Steps To Reproduce

Codesandbox link:- https://codesandbox.io/s/thirsty-butterfly-6i0ct

**Comment by tmm** [comment]
It works fine for WalletConnect and WalletLink. MetaMask (and some other injected providers) don't support programmatically disconnecting.

Check out [this comment](https://github.com/tmm/wagmi/issues/38#issuecomment-1006685000) for more info.

I also [commented](https://github.com/MetaMask/metamask-extension/issues/10353#issuecomment-1011129684) on an issue in the MetaMask repo.

**Comment by Deveshb15** [comment]
@tmm Thank you for the reply, hope metamask fixes this soon!

**Comment by murathanje** [comment]
Did you solve this issue? I get same issue and I need to solve that. What can I do?

**Comment by murathanje** [comment]
Did you solve this issue? I get same issue and I need to solve that. What can I do?

**Comment by refatsherfedinov** [comment]
@murathanje @Deveshb15 
just add small timeout for disconnect and it will work
```
        // Delayed disconnect
        const timer = setTimeout(() => {
            disconnect();
        }, 100);

        return () => clearTimeout(timer);
```
