### ISSUE TITLE
[bug] next build failing in ci with:  "TypeError: Cannot read properties of undefined (reading 'rpcUrls')"

### ISSUE THREAD

**Issue by jtlacci** [tmm/wagmi#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.9

### Current Behavior

currently running into this issue in our ci
node: 16.14.2
npm: 8
next: 12.1.5
```
> next build
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Compiled successfully
info  - Collecting page data...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
TypeError: Cannot read properties of undefined (reading 'rpcUrls')
    at /home/runner/work/web/web/node_modules/@wagmi/core/providers/infura/dist/wagmi-core-providers-infura.cjs.prod.js:17:[16](https://github.com/orcaprotocol/web/runs/7266495405?check_suite_focus=true#step:8:17)
    at configureChains (/home/runner/work/web/web/node_modules/@wagmi/core/dist/wagmi-core.cjs.prod.js:37:25)
    at /home/runner/work/web/web/.next/server/chunks/[17](https://github.com/orcaprotocol/web/runs/7266495405?check_suite_focus=true#step:8:18)6.js:8556:106 {
  type: 'TypeError'
}
```
the weird thing is i'm unable to replicate locally

**Comment by tmm** [comment]
Thanks for reporting! Please add a minimal reproducible example and re-open this issue.

**Comment by ikemHood** [comment]
Having same issue

@tmm 

my file structure

`export function AppChains({ mode }) {
  if (mode === "testnet") {
    return {
      id: 568,
      name: "DogeChain",
      network: "Dogechain",
      nativeCurrency: {
        decimals: 18,
        name: "DogeChain",
        symbol: "wDoge",
      },
      rpcUrls: {
        default: "https://rpc-testnet.dogechain.dog",
      },
      blockExplorers: {
        default: {
          name: "DogeExploree",
          url: "https://explorer-testnet.dogechain.dog",
        },
        etherscan: {
          name: "DogeExplore",
          url: "https://explorer-testnet.dogechain.dog",
        },
      },
      testnet: true,
    };
  } else if (mode === "mainnet") {
    return {
      id: 2000,
      name: "DogeChain",
      network: "Dogechain",
      nativeCurrency: {
        decimals: 18,
        name: "DogeChain",
        symbol: "wDoge",
      },
      rpcUrls: {
        default: "https://rpc01-sg.dogechain.dog",
      },
      blockExplorers: {
        default: {
          name: "DogeExploree",
          url: "https://explorer.dogechain.dog",
        },
        etherscan: {
          name: "DogeExplore",
          url: "https://explorer.dogechain.dog",
        },
      },
      testnet: false,
    };
  }
}`

`import { AppChains } from './Contracts/ChainSetup';

const appChains = AppChains({mode: process.env.MODE})
const { chains, provider } = configureChains(
  [appChains], // [DogeChain, DogeChainTest]
  [jsonRpcProvider({rpc: (chain) => ({http: chain?.rpcUrls.default})})],
)`



error i get
`wagmi-core-providers-jsonRpc.esm.js:16 Uncaught TypeError: Cannot read properties of undefined (reading 'rpcUrls')
    at wagmi-core-providers-jsonRpc.esm.js:16:1
    at configureChains (wagmi-core.esm.js:32:1)
    at ./src/index.js (index.js:13:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1`
