### ISSUE TITLE
[bug]Wagmi not support for expo

### ISSUE THREAD

**Issue by jeff0723** [tmm/wagmi#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.5.9

### Current Behavior

After ```yarn add wagmi``` my expo app is not going to run. It's always showing
<img width="325" alt="Screenshot 2022-07-14 at 20 50 48" src="https://user-images.githubusercontent.com/38219877/178986409-a4e3438c-fd55-4ab4-9521-a604401fe3c5.png">

**Comment by tmm** [comment]
wagmi's client [storage defaults to `window.localStorage`](https://wagmi.sh/docs/client#storage-optional=) so you'll need to [pass your own storage implementation](https://github.com/tmm/wagmi/discussions/533#discussioncomment-2885887) for React Native to work.
