### ISSUE TITLE
[bug] getProvider returns wrong provider

### ISSUE THREAD

**Issue by jappyjan** [tmm/wagmi#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.0.17

### Current Behavior

1. i select localhost network (chain-id 1337) in metamask
2. i connect wagmi to metamask using useConnect() hook
3. i get myself a provider using getProvider()
4. i log the provider instance to the console
4. in the console i see that the property "_network" of the provider says that it is connected to mainnet (homeastead, chain id 1)

when i instead create a new ethers instance manually by providing the injected ethereum instance from window into the ethers web3 provider constructor, the network is correctly set to localhost.

### Expected Behavior

it should connect to localhost, not mainnet

### Steps To Reproduce

see current behaviour

### Anything else?

just tried using "useNetwork" to check what wagmi thinks is the current network...
useNetwork correctly return 1337 as chain id... weird

**Comment by andreujuanc** [comment]
I also have the same issue. I explicitly set the chains only to [31337] (hardhat) and the provider from useProvider comes chainId:1
Let me know if you've found a workaround.

Cheers.

**Comment by jappyjan** [comment]
Yes i found a workaround.

Instead of using getProvider, instead I use useAccount()

And from the returned data I then get the signer (I don't need the provider, only the signer) by getting accountState.data.connector.getSigner()

I hope this helps you.
But still, I would love to just be able to use useProvider...

**Comment by tmm** [comment]
Closing as @andreujuanc's [comment](https://github.com/tmm/wagmi/issues/71#issuecomment-1013748986) allows you to set up a network-aware ethers.js Provider.

**Comment by andreujuanc** [comment]
@tmm  Maybe the default behaviour should be as per my workaround? Is this something that can be fixed? or maybe documented better?
Thanks

**Comment by tmm** [comment]
We should add a guide about working with Hardhat. ethers.js `getDefaultProvider` creates and uses several other providers under the hood (some that I don't think work with Hardhat, like the Etherscan provider).

Also, I just added a Hardhat chain to `chain` lookup object:

```ts
import { chain } from 'wagmi'

chain.hardhat
```

**Comment by ConnorSB13** [comment]
> Yes i found a workaround.
> 
> Instead of using getProvider, instead I use useAccount()
> 
> And from the returned data I then get the signer (I don't need the provider, only the signer) by getting accountState.data.connector.getSigner()
> 
> I hope this helps you. But still, I would love to just be able to use useProvider...

You could use `useSigner()` directly.
