### ISSUE TITLE
[bug] Hydration Error with React 18 and Next 12

### ISSUE THREAD

**Issue by farreldarian** [tmm/wagmi#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.9

### Current Behavior

Using any wagmi hooks throws hydration error, probably because of React 18 but #307 has been resolved.

![Untitled_AdobeExpress (1)](https://user-images.githubusercontent.com/62016900/179261648-efec211d-a2b8-4a6a-bc10-a461a5f91c77.gif)

### Expected Behavior

Works normally.

### Steps To Reproduce

I made a repo to reproduce this behavior, StackBlitz somehow throws more unnecessary errors. It's a clean install `create-next-app` with wagmi, ethers, and rainbowkit. Removing rainbowkit doesn't solve either.

1. `pnpm isntall`
2. `pnpm dev`
3. Go to "http://localhost:3000"
4. Refresh several times

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/farreldarian/wagmi-reproduce-1

### Anything else?

Env:
M1 Pro
MacOS 12.4 
Node v16.15.1

**Comment by jxom** [comment]
wagmi does not have a first class solution for SSR yet. See https://github.com/tmm/wagmi/issues/542#issuecomment-1144178142 for workarounds.

**Comment by farreldarian** [comment]
I manage to solve this by changing the storage with `js-cookie` like in #689, haven't yet consider the trade-off.
