### ISSUE TITLE
[bug] Found 2 breaking issues in the React Vite example.

### ISSUE THREAD

**Issue by Omar-Aziz** [tmm/wagmi#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

I cloned the vite-react example from https://github.com/tmm/wagmi/tree/main/examples/vite-react and found the following issues:

- `MirrorERC20FactoryContract` is imported but it doesn't exist: https://github.com/tmm/wagmi/blob/21d6de32e4cdbf40a6d9c01f0993876af33f89b7/examples/vite-react/src/components/ContractFunction.tsx#L6
- The `tsconfig.json` file extends another config file that's not accessible: https://github.com/tmm/wagmi/blob/21d6de32e4cdbf40a6d9c01f0993876af33f89b7/examples/vite-react/tsconfig.json#L2

### Expected Behavior

The example should run as a standalone without breaking issues. Currently cloning the vite-react example locally or using stackblitz or codestandbox fails to run.

### Steps To Reproduce

Stackblitz: https://stackblitz.com/github/tmm/wagmi/tree/main/examples/vite-react
Codesandbox: https://githubbox.com/tmm/wagmi/tree/main/examples/vite-react

### Anything else?

Use a separate repo for the examples to ensure the examples are not relying on external files that are not part of dependencies.

**Comment by tmm** [comment]
Updated the examples so they are standalone.

Previously had it set up for local development to test while building out wagmi.

**Comment by Omar-Aziz** [comment]
The nextjs example is still unable to function as a standalone. It has a `babel.config.js` which exports `../../babel.config` which doesn't exist anywhere in the next example directory. I propose using a separate repo.

**Comment by tmm** [comment]
Fixed. That file was unnecessary.
