### ISSUE TITLE
[bug] Useing dynamic args with `useContractRead` occurred some error.

### ISSUE THREAD

**Issue by zouhangwithsweet** [tmm/wagmi#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.8

### Current Behavior

I have to dynamic render component. Then occurred these error
<img width="584" alt="image" src="https://user-images.githubusercontent.com/21095710/179669429-b3483b3d-6f07-4517-8864-c02bae3e5f46.png">

### Expected Behavior

It can work well with dynamic args

### Steps To Reproduce

**Mini reproduction:** https://github.com/fisand/vite-antd-seed/tree/test_dynamic_args
**Branch**: `test_dynamic_args`
**Steps**
- Clone this repo
- pnpm i
- pnpm run dev
- waiting 3s

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/fisand/vite-antd-seed/tree/test_dynamic_args

**Comment by jxom** [comment]
You don't need to initialize an `Interface` for `contractInterface`, you can just pass in the ABI JSON:

```diff
const WAGMI_ABI_INTERFACE = new Interface(WAGMI_ABI)

export const useWagmiContract = () => {
  const address = useWagmiContractAddress()
  return useMemo(
    () => ({
      addressOrName: address!,
-    contractInterface: new Interface(WAGMI_ABI),
+.  contractInterface: WAGMI_ABI
    }),
    [address]
  )
}
```
