### ISSUE TITLE
[bug] value does not exist in type 'Overrides'

### ISSUE THREAD

**Issue by seeARMS** [tmm/wagmi#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.5

### Current Behavior

I have a contractWrite:

```
  const [{ data, error, loading }, write] = useContractWrite(
    {
      addressOrName: SMART_CONTRACT, // Ropsten ERC1155 contract
      contractInterface: AccessTokenABI.abi,
      signerOrProvider: signerData,
    },
    "buy"
  )
```

I'm calling the write method and passing `value` in `overrides`:

```
    const writeResult = await write({
      args: [id],
      overrides: {
        gasLimit: "1000000",
        value: ethers.utils.parseEther("0.01"),
      },
    })

```

I'm getting a typescript error:

```
Object literal may only specify known properties, and 'value' does not exist in type 'Overrides'.
```

The actual request works as intended, so I'm not sure why TS is throwing an error. Couldn't find anything in the ethers doc either.

### Expected Behavior

No typescript error when passing value as an override.

### Steps To Reproduce

Use the above code.

### Anything else?

![Uploading image.png…]()

**Comment by tmm** [comment]
https://github.com/tmm/wagmi/commit/b7018a64d88c9805a6fe0a4a41963ea6a33099a6
